// Code generated by ent, DO NOT EDIT.

package lotterydraw

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lotterydraw type in the database.
	Label = "lottery_draw"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldPrizeID holds the string denoting the prize_id field in the database.
	FieldPrizeID = "prize_id"
	// FieldPrizeName holds the string denoting the prize_name field in the database.
	FieldPrizeName = "prize_name"
	// FieldPrizeType holds the string denoting the prize_type field in the database.
	FieldPrizeType = "prize_type"
	// FieldPrizeValue holds the string denoting the prize_value field in the database.
	FieldPrizeValue = "prize_value"
	// FieldRulesVersion holds the string denoting the rules_version field in the database.
	FieldRulesVersion = "rules_version"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldBalanceSpentAtDraw holds the string denoting the balance_spent_at_draw field in the database.
	FieldBalanceSpentAtDraw = "balance_spent_at_draw"
	// FieldFulfillmentStatus holds the string denoting the fulfillment_status field in the database.
	FieldFulfillmentStatus = "fulfillment_status"
	// FieldFulfilledAt holds the string denoting the fulfilled_at field in the database.
	FieldFulfilledAt = "fulfilled_at"
	// FieldFulfillmentError holds the string denoting the fulfillment_error field in the database.
	FieldFulfillmentError = "fulfillment_error"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the lotterydraw in the database.
	Table = "lottery_draws"
)

// Columns holds all SQL columns for lotterydraw fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldActivityID,
	FieldPrizeID,
	FieldPrizeName,
	FieldPrizeType,
	FieldPrizeValue,
	FieldRulesVersion,
	FieldSource,
	FieldBalanceSpentAtDraw,
	FieldFulfillmentStatus,
	FieldFulfilledAt,
	FieldFulfillmentError,
	FieldIdempotencyKey,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PrizeNameValidator is a validator for the "prize_name" field. It is called by the builders before save.
	PrizeNameValidator func(string) error
	// PrizeTypeValidator is a validator for the "prize_type" field. It is called by the builders before save.
	PrizeTypeValidator func(string) error
	// DefaultPrizeValue holds the default value on creation for the "prize_value" field.
	DefaultPrizeValue float64
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultBalanceSpentAtDraw holds the default value on creation for the "balance_spent_at_draw" field.
	DefaultBalanceSpentAtDraw float64
	// DefaultFulfillmentStatus holds the default value on creation for the "fulfillment_status" field.
	DefaultFulfillmentStatus string
	// FulfillmentStatusValidator is a validator for the "fulfillment_status" field. It is called by the builders before save.
	FulfillmentStatusValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryDraw queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByPrizeID orders the results by the prize_id field.
func ByPrizeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeID, opts...).ToFunc()
}

// ByPrizeName orders the results by the prize_name field.
func ByPrizeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeName, opts...).ToFunc()
}

// ByPrizeType orders the results by the prize_type field.
func ByPrizeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeType, opts...).ToFunc()
}

// ByPrizeValue orders the results by the prize_value field.
func ByPrizeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeValue, opts...).ToFunc()
}

// ByRulesVersion orders the results by the rules_version field.
func ByRulesVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRulesVersion, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByBalanceSpentAtDraw orders the results by the balance_spent_at_draw field.
func ByBalanceSpentAtDraw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceSpentAtDraw, opts...).ToFunc()
}

// ByFulfillmentStatus orders the results by the fulfillment_status field.
func ByFulfillmentStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFulfillmentStatus, opts...).ToFunc()
}

// ByFulfilledAt orders the results by the fulfilled_at field.
func ByFulfilledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFulfilledAt, opts...).ToFunc()
}

// ByFulfillmentError orders the results by the fulfillment_error field.
func ByFulfillmentError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFulfillmentError, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
