// Code generated by ent, DO NOT EDIT.

package lotterydraw

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldUserID, v))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldActivityID, v))
}

// PrizeID applies equality check predicate on the "prize_id" field. It's identical to PrizeIDEQ.
func PrizeID(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeID, v))
}

// PrizeName applies equality check predicate on the "prize_name" field. It's identical to PrizeNameEQ.
func PrizeName(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeName, v))
}

// PrizeType applies equality check predicate on the "prize_type" field. It's identical to PrizeTypeEQ.
func PrizeType(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeType, v))
}

// PrizeValue applies equality check predicate on the "prize_value" field. It's identical to PrizeValueEQ.
func PrizeValue(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeValue, v))
}

// RulesVersion applies equality check predicate on the "rules_version" field. It's identical to RulesVersionEQ.
func RulesVersion(v int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldRulesVersion, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldSource, v))
}

// BalanceSpentAtDraw applies equality check predicate on the "balance_spent_at_draw" field. It's identical to BalanceSpentAtDrawEQ.
func BalanceSpentAtDraw(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldBalanceSpentAtDraw, v))
}

// FulfillmentStatus applies equality check predicate on the "fulfillment_status" field. It's identical to FulfillmentStatusEQ.
func FulfillmentStatus(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldFulfillmentStatus, v))
}

// FulfilledAt applies equality check predicate on the "fulfilled_at" field. It's identical to FulfilledAtEQ.
func FulfilledAt(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldFulfilledAt, v))
}

// FulfillmentError applies equality check predicate on the "fulfillment_error" field. It's identical to FulfillmentErrorEQ.
func FulfillmentError(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldFulfillmentError, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldIdempotencyKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldUserID, v))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldActivityID, vs...))
}

// ActivityIDGT applies the GT predicate on the "activity_id" field.
func ActivityIDGT(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldActivityID, v))
}

// ActivityIDGTE applies the GTE predicate on the "activity_id" field.
func ActivityIDGTE(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldActivityID, v))
}

// ActivityIDLT applies the LT predicate on the "activity_id" field.
func ActivityIDLT(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldActivityID, v))
}

// ActivityIDLTE applies the LTE predicate on the "activity_id" field.
func ActivityIDLTE(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldActivityID, v))
}

// PrizeIDEQ applies the EQ predicate on the "prize_id" field.
func PrizeIDEQ(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeID, v))
}

// PrizeIDNEQ applies the NEQ predicate on the "prize_id" field.
func PrizeIDNEQ(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldPrizeID, v))
}

// PrizeIDIn applies the In predicate on the "prize_id" field.
func PrizeIDIn(vs ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldPrizeID, vs...))
}

// PrizeIDNotIn applies the NotIn predicate on the "prize_id" field.
func PrizeIDNotIn(vs ...int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldPrizeID, vs...))
}

// PrizeIDGT applies the GT predicate on the "prize_id" field.
func PrizeIDGT(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldPrizeID, v))
}

// PrizeIDGTE applies the GTE predicate on the "prize_id" field.
func PrizeIDGTE(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldPrizeID, v))
}

// PrizeIDLT applies the LT predicate on the "prize_id" field.
func PrizeIDLT(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldPrizeID, v))
}

// PrizeIDLTE applies the LTE predicate on the "prize_id" field.
func PrizeIDLTE(v int64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldPrizeID, v))
}

// PrizeIDIsNil applies the IsNil predicate on the "prize_id" field.
func PrizeIDIsNil() predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIsNull(FieldPrizeID))
}

// PrizeIDNotNil applies the NotNil predicate on the "prize_id" field.
func PrizeIDNotNil() predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotNull(FieldPrizeID))
}

// PrizeNameEQ applies the EQ predicate on the "prize_name" field.
func PrizeNameEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeName, v))
}

// PrizeNameNEQ applies the NEQ predicate on the "prize_name" field.
func PrizeNameNEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldPrizeName, v))
}

// PrizeNameIn applies the In predicate on the "prize_name" field.
func PrizeNameIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldPrizeName, vs...))
}

// PrizeNameNotIn applies the NotIn predicate on the "prize_name" field.
func PrizeNameNotIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldPrizeName, vs...))
}

// PrizeNameGT applies the GT predicate on the "prize_name" field.
func PrizeNameGT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldPrizeName, v))
}

// PrizeNameGTE applies the GTE predicate on the "prize_name" field.
func PrizeNameGTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldPrizeName, v))
}

// PrizeNameLT applies the LT predicate on the "prize_name" field.
func PrizeNameLT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldPrizeName, v))
}

// PrizeNameLTE applies the LTE predicate on the "prize_name" field.
func PrizeNameLTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldPrizeName, v))
}

// PrizeNameContains applies the Contains predicate on the "prize_name" field.
func PrizeNameContains(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContains(FieldPrizeName, v))
}

// PrizeNameHasPrefix applies the HasPrefix predicate on the "prize_name" field.
func PrizeNameHasPrefix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasPrefix(FieldPrizeName, v))
}

// PrizeNameHasSuffix applies the HasSuffix predicate on the "prize_name" field.
func PrizeNameHasSuffix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasSuffix(FieldPrizeName, v))
}

// PrizeNameEqualFold applies the EqualFold predicate on the "prize_name" field.
func PrizeNameEqualFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEqualFold(FieldPrizeName, v))
}

// PrizeNameContainsFold applies the ContainsFold predicate on the "prize_name" field.
func PrizeNameContainsFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContainsFold(FieldPrizeName, v))
}

// PrizeTypeEQ applies the EQ predicate on the "prize_type" field.
func PrizeTypeEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeType, v))
}

// PrizeTypeNEQ applies the NEQ predicate on the "prize_type" field.
func PrizeTypeNEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldPrizeType, v))
}

// PrizeTypeIn applies the In predicate on the "prize_type" field.
func PrizeTypeIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldPrizeType, vs...))
}

// PrizeTypeNotIn applies the NotIn predicate on the "prize_type" field.
func PrizeTypeNotIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldPrizeType, vs...))
}

// PrizeTypeGT applies the GT predicate on the "prize_type" field.
func PrizeTypeGT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldPrizeType, v))
}

// PrizeTypeGTE applies the GTE predicate on the "prize_type" field.
func PrizeTypeGTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldPrizeType, v))
}

// PrizeTypeLT applies the LT predicate on the "prize_type" field.
func PrizeTypeLT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldPrizeType, v))
}

// PrizeTypeLTE applies the LTE predicate on the "prize_type" field.
func PrizeTypeLTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldPrizeType, v))
}

// PrizeTypeContains applies the Contains predicate on the "prize_type" field.
func PrizeTypeContains(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContains(FieldPrizeType, v))
}

// PrizeTypeHasPrefix applies the HasPrefix predicate on the "prize_type" field.
func PrizeTypeHasPrefix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasPrefix(FieldPrizeType, v))
}

// PrizeTypeHasSuffix applies the HasSuffix predicate on the "prize_type" field.
func PrizeTypeHasSuffix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasSuffix(FieldPrizeType, v))
}

// PrizeTypeEqualFold applies the EqualFold predicate on the "prize_type" field.
func PrizeTypeEqualFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEqualFold(FieldPrizeType, v))
}

// PrizeTypeContainsFold applies the ContainsFold predicate on the "prize_type" field.
func PrizeTypeContainsFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContainsFold(FieldPrizeType, v))
}

// PrizeValueEQ applies the EQ predicate on the "prize_value" field.
func PrizeValueEQ(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldPrizeValue, v))
}

// PrizeValueNEQ applies the NEQ predicate on the "prize_value" field.
func PrizeValueNEQ(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldPrizeValue, v))
}

// PrizeValueIn applies the In predicate on the "prize_value" field.
func PrizeValueIn(vs ...float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldPrizeValue, vs...))
}

// PrizeValueNotIn applies the NotIn predicate on the "prize_value" field.
func PrizeValueNotIn(vs ...float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldPrizeValue, vs...))
}

// PrizeValueGT applies the GT predicate on the "prize_value" field.
func PrizeValueGT(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldPrizeValue, v))
}

// PrizeValueGTE applies the GTE predicate on the "prize_value" field.
func PrizeValueGTE(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldPrizeValue, v))
}

// PrizeValueLT applies the LT predicate on the "prize_value" field.
func PrizeValueLT(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldPrizeValue, v))
}

// PrizeValueLTE applies the LTE predicate on the "prize_value" field.
func PrizeValueLTE(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldPrizeValue, v))
}

// RulesVersionEQ applies the EQ predicate on the "rules_version" field.
func RulesVersionEQ(v int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldRulesVersion, v))
}

// RulesVersionNEQ applies the NEQ predicate on the "rules_version" field.
func RulesVersionNEQ(v int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldRulesVersion, v))
}

// RulesVersionIn applies the In predicate on the "rules_version" field.
func RulesVersionIn(vs ...int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldRulesVersion, vs...))
}

// RulesVersionNotIn applies the NotIn predicate on the "rules_version" field.
func RulesVersionNotIn(vs ...int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldRulesVersion, vs...))
}

// RulesVersionGT applies the GT predicate on the "rules_version" field.
func RulesVersionGT(v int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldRulesVersion, v))
}

// RulesVersionGTE applies the GTE predicate on the "rules_version" field.
func RulesVersionGTE(v int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldRulesVersion, v))
}

// RulesVersionLT applies the LT predicate on the "rules_version" field.
func RulesVersionLT(v int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldRulesVersion, v))
}

// RulesVersionLTE applies the LTE predicate on the "rules_version" field.
func RulesVersionLTE(v int) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldRulesVersion, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContainsFold(FieldSource, v))
}

// BalanceSpentAtDrawEQ applies the EQ predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawEQ(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldBalanceSpentAtDraw, v))
}

// BalanceSpentAtDrawNEQ applies the NEQ predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawNEQ(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldBalanceSpentAtDraw, v))
}

// BalanceSpentAtDrawIn applies the In predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawIn(vs ...float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldBalanceSpentAtDraw, vs...))
}

// BalanceSpentAtDrawNotIn applies the NotIn predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawNotIn(vs ...float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldBalanceSpentAtDraw, vs...))
}

// BalanceSpentAtDrawGT applies the GT predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawGT(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldBalanceSpentAtDraw, v))
}

// BalanceSpentAtDrawGTE applies the GTE predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawGTE(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldBalanceSpentAtDraw, v))
}

// BalanceSpentAtDrawLT applies the LT predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawLT(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldBalanceSpentAtDraw, v))
}

// BalanceSpentAtDrawLTE applies the LTE predicate on the "balance_spent_at_draw" field.
func BalanceSpentAtDrawLTE(v float64) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldBalanceSpentAtDraw, v))
}

// FulfillmentStatusEQ applies the EQ predicate on the "fulfillment_status" field.
func FulfillmentStatusEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldFulfillmentStatus, v))
}

// FulfillmentStatusNEQ applies the NEQ predicate on the "fulfillment_status" field.
func FulfillmentStatusNEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldFulfillmentStatus, v))
}

// FulfillmentStatusIn applies the In predicate on the "fulfillment_status" field.
func FulfillmentStatusIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldFulfillmentStatus, vs...))
}

// FulfillmentStatusNotIn applies the NotIn predicate on the "fulfillment_status" field.
func FulfillmentStatusNotIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldFulfillmentStatus, vs...))
}

// FulfillmentStatusGT applies the GT predicate on the "fulfillment_status" field.
func FulfillmentStatusGT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldFulfillmentStatus, v))
}

// FulfillmentStatusGTE applies the GTE predicate on the "fulfillment_status" field.
func FulfillmentStatusGTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldFulfillmentStatus, v))
}

// FulfillmentStatusLT applies the LT predicate on the "fulfillment_status" field.
func FulfillmentStatusLT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldFulfillmentStatus, v))
}

// FulfillmentStatusLTE applies the LTE predicate on the "fulfillment_status" field.
func FulfillmentStatusLTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldFulfillmentStatus, v))
}

// FulfillmentStatusContains applies the Contains predicate on the "fulfillment_status" field.
func FulfillmentStatusContains(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContains(FieldFulfillmentStatus, v))
}

// FulfillmentStatusHasPrefix applies the HasPrefix predicate on the "fulfillment_status" field.
func FulfillmentStatusHasPrefix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasPrefix(FieldFulfillmentStatus, v))
}

// FulfillmentStatusHasSuffix applies the HasSuffix predicate on the "fulfillment_status" field.
func FulfillmentStatusHasSuffix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasSuffix(FieldFulfillmentStatus, v))
}

// FulfillmentStatusEqualFold applies the EqualFold predicate on the "fulfillment_status" field.
func FulfillmentStatusEqualFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEqualFold(FieldFulfillmentStatus, v))
}

// FulfillmentStatusContainsFold applies the ContainsFold predicate on the "fulfillment_status" field.
func FulfillmentStatusContainsFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContainsFold(FieldFulfillmentStatus, v))
}

// FulfilledAtEQ applies the EQ predicate on the "fulfilled_at" field.
func FulfilledAtEQ(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldFulfilledAt, v))
}

// FulfilledAtNEQ applies the NEQ predicate on the "fulfilled_at" field.
func FulfilledAtNEQ(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldFulfilledAt, v))
}

// FulfilledAtIn applies the In predicate on the "fulfilled_at" field.
func FulfilledAtIn(vs ...time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldFulfilledAt, vs...))
}

// FulfilledAtNotIn applies the NotIn predicate on the "fulfilled_at" field.
func FulfilledAtNotIn(vs ...time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldFulfilledAt, vs...))
}

// FulfilledAtGT applies the GT predicate on the "fulfilled_at" field.
func FulfilledAtGT(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldFulfilledAt, v))
}

// FulfilledAtGTE applies the GTE predicate on the "fulfilled_at" field.
func FulfilledAtGTE(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldFulfilledAt, v))
}

// FulfilledAtLT applies the LT predicate on the "fulfilled_at" field.
func FulfilledAtLT(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldFulfilledAt, v))
}

// FulfilledAtLTE applies the LTE predicate on the "fulfilled_at" field.
func FulfilledAtLTE(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldFulfilledAt, v))
}

// FulfilledAtIsNil applies the IsNil predicate on the "fulfilled_at" field.
func FulfilledAtIsNil() predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIsNull(FieldFulfilledAt))
}

// FulfilledAtNotNil applies the NotNil predicate on the "fulfilled_at" field.
func FulfilledAtNotNil() predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotNull(FieldFulfilledAt))
}

// FulfillmentErrorEQ applies the EQ predicate on the "fulfillment_error" field.
func FulfillmentErrorEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldFulfillmentError, v))
}

// FulfillmentErrorNEQ applies the NEQ predicate on the "fulfillment_error" field.
func FulfillmentErrorNEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldFulfillmentError, v))
}

// FulfillmentErrorIn applies the In predicate on the "fulfillment_error" field.
func FulfillmentErrorIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldFulfillmentError, vs...))
}

// FulfillmentErrorNotIn applies the NotIn predicate on the "fulfillment_error" field.
func FulfillmentErrorNotIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldFulfillmentError, vs...))
}

// FulfillmentErrorGT applies the GT predicate on the "fulfillment_error" field.
func FulfillmentErrorGT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldFulfillmentError, v))
}

// FulfillmentErrorGTE applies the GTE predicate on the "fulfillment_error" field.
func FulfillmentErrorGTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldFulfillmentError, v))
}

// FulfillmentErrorLT applies the LT predicate on the "fulfillment_error" field.
func FulfillmentErrorLT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldFulfillmentError, v))
}

// FulfillmentErrorLTE applies the LTE predicate on the "fulfillment_error" field.
func FulfillmentErrorLTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldFulfillmentError, v))
}

// FulfillmentErrorContains applies the Contains predicate on the "fulfillment_error" field.
func FulfillmentErrorContains(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContains(FieldFulfillmentError, v))
}

// FulfillmentErrorHasPrefix applies the HasPrefix predicate on the "fulfillment_error" field.
func FulfillmentErrorHasPrefix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasPrefix(FieldFulfillmentError, v))
}

// FulfillmentErrorHasSuffix applies the HasSuffix predicate on the "fulfillment_error" field.
func FulfillmentErrorHasSuffix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasSuffix(FieldFulfillmentError, v))
}

// FulfillmentErrorIsNil applies the IsNil predicate on the "fulfillment_error" field.
func FulfillmentErrorIsNil() predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIsNull(FieldFulfillmentError))
}

// FulfillmentErrorNotNil applies the NotNil predicate on the "fulfillment_error" field.
func FulfillmentErrorNotNil() predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotNull(FieldFulfillmentError))
}

// FulfillmentErrorEqualFold applies the EqualFold predicate on the "fulfillment_error" field.
func FulfillmentErrorEqualFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEqualFold(FieldFulfillmentError, v))
}

// FulfillmentErrorContainsFold applies the ContainsFold predicate on the "fulfillment_error" field.
func FulfillmentErrorContainsFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContainsFold(FieldFulfillmentError, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryDraw) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryDraw) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryDraw) predicate.LotteryDraw {
	return predicate.LotteryDraw(sql.NotPredicates(p))
}
