// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryDrawUpdate is the builder for updating LotteryDraw entities.
type LotteryDrawUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryDrawMutation
}

// Where appends a list predicates to the LotteryDrawUpdate builder.
func (_u *LotteryDrawUpdate) Where(ps ...predicate.LotteryDraw) *LotteryDrawUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawUpdate) SetUserID(v int64) *LotteryDrawUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableUserID(v *int64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryDrawUpdate) AddUserID(v int64) *LotteryDrawUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryDrawUpdate) SetActivityID(v int64) *LotteryDrawUpdate {
	_u.mutation.ResetActivityID()
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableActivityID(v *int64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// AddActivityID adds value to the "activity_id" field.
func (_u *LotteryDrawUpdate) AddActivityID(v int64) *LotteryDrawUpdate {
	_u.mutation.AddActivityID(v)
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *LotteryDrawUpdate) SetPrizeID(v int64) *LotteryDrawUpdate {
	_u.mutation.ResetPrizeID()
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillablePrizeID(v *int64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// AddPrizeID adds value to the "prize_id" field.
func (_u *LotteryDrawUpdate) AddPrizeID(v int64) *LotteryDrawUpdate {
	_u.mutation.AddPrizeID(v)
	return _u
}

// ClearPrizeID clears the value of the "prize_id" field.
func (_u *LotteryDrawUpdate) ClearPrizeID() *LotteryDrawUpdate {
	_u.mutation.ClearPrizeID()
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawUpdate) SetPrizeName(v string) *LotteryDrawUpdate {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillablePrizeName(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetPrizeType sets the "prize_type" field.
func (_u *LotteryDrawUpdate) SetPrizeType(v string) *LotteryDrawUpdate {
	_u.mutation.SetPrizeType(v)
	return _u
}

// SetNillablePrizeType sets the "prize_type" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillablePrizeType(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetPrizeType(*v)
	}
	return _u
}

// SetPrizeValue sets the "prize_value" field.
func (_u *LotteryDrawUpdate) SetPrizeValue(v float64) *LotteryDrawUpdate {
	_u.mutation.ResetPrizeValue()
	_u.mutation.SetPrizeValue(v)
	return _u
}

// SetNillablePrizeValue sets the "prize_value" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillablePrizeValue(v *float64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetPrizeValue(*v)
	}
	return _u
}

// AddPrizeValue adds value to the "prize_value" field.
func (_u *LotteryDrawUpdate) AddPrizeValue(v float64) *LotteryDrawUpdate {
	_u.mutation.AddPrizeValue(v)
	return _u
}

// SetRulesVersion sets the "rules_version" field.
func (_u *LotteryDrawUpdate) SetRulesVersion(v int) *LotteryDrawUpdate {
	_u.mutation.ResetRulesVersion()
	_u.mutation.SetRulesVersion(v)
	return _u
}

// SetNillableRulesVersion sets the "rules_version" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableRulesVersion(v *int) *LotteryDrawUpdate {
	if v != nil {
		_u.SetRulesVersion(*v)
	}
	return _u
}

// AddRulesVersion adds value to the "rules_version" field.
func (_u *LotteryDrawUpdate) AddRulesVersion(v int) *LotteryDrawUpdate {
	_u.mutation.AddRulesVersion(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *LotteryDrawUpdate) SetSource(v string) *LotteryDrawUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableSource(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetBalanceSpentAtDraw sets the "balance_spent_at_draw" field.
func (_u *LotteryDrawUpdate) SetBalanceSpentAtDraw(v float64) *LotteryDrawUpdate {
	_u.mutation.ResetBalanceSpentAtDraw()
	_u.mutation.SetBalanceSpentAtDraw(v)
	return _u
}

// SetNillableBalanceSpentAtDraw sets the "balance_spent_at_draw" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableBalanceSpentAtDraw(v *float64) *LotteryDrawUpdate {
	if v != nil {
		_u.SetBalanceSpentAtDraw(*v)
	}
	return _u
}

// AddBalanceSpentAtDraw adds value to the "balance_spent_at_draw" field.
func (_u *LotteryDrawUpdate) AddBalanceSpentAtDraw(v float64) *LotteryDrawUpdate {
	_u.mutation.AddBalanceSpentAtDraw(v)
	return _u
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (_u *LotteryDrawUpdate) SetFulfillmentStatus(v string) *LotteryDrawUpdate {
	_u.mutation.SetFulfillmentStatus(v)
	return _u
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableFulfillmentStatus(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetFulfillmentStatus(*v)
	}
	return _u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_u *LotteryDrawUpdate) SetFulfilledAt(v time.Time) *LotteryDrawUpdate {
	_u.mutation.SetFulfilledAt(v)
	return _u
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableFulfilledAt(v *time.Time) *LotteryDrawUpdate {
	if v != nil {
		_u.SetFulfilledAt(*v)
	}
	return _u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (_u *LotteryDrawUpdate) ClearFulfilledAt() *LotteryDrawUpdate {
	_u.mutation.ClearFulfilledAt()
	return _u
}

// SetFulfillmentError sets the "fulfillment_error" field.
func (_u *LotteryDrawUpdate) SetFulfillmentError(v string) *LotteryDrawUpdate {
	_u.mutation.SetFulfillmentError(v)
	return _u
}

// SetNillableFulfillmentError sets the "fulfillment_error" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableFulfillmentError(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetFulfillmentError(*v)
	}
	return _u
}

// ClearFulfillmentError clears the value of the "fulfillment_error" field.
func (_u *LotteryDrawUpdate) ClearFulfillmentError() *LotteryDrawUpdate {
	_u.mutation.ClearFulfillmentError()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *LotteryDrawUpdate) SetIdempotencyKey(v string) *LotteryDrawUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *LotteryDrawUpdate) SetNillableIdempotencyKey(v *string) *LotteryDrawUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// Mutation returns the LotteryDrawMutation object of the builder.
func (_u *LotteryDrawUpdate) Mutation() *LotteryDrawMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryDrawUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryDrawUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryDrawUpdate) check() error {
	if v, ok := _u.mutation.PrizeName(); ok {
		if err := lotterydraw.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeType(); ok {
		if err := lotterydraw.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := lotterydraw.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FulfillmentStatus(); ok {
		if err := lotterydraw.FulfillmentStatusValidator(v); err != nil {
			return &ValidationError{Name: "fulfillment_status", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.fulfillment_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := lotterydraw.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.idempotency_key": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryDrawUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterydraw.Table, lotterydraw.Columns, sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(lotterydraw.FieldActivityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActivityID(); ok {
		_spec.AddField(lotterydraw.FieldActivityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeID(); ok {
		_spec.SetField(lotterydraw.FieldPrizeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizeID(); ok {
		_spec.AddField(lotterydraw.FieldPrizeID, field.TypeInt64, value)
	}
	if _u.mutation.PrizeIDCleared() {
		_spec.ClearField(lotterydraw.FieldPrizeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydraw.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeType(); ok {
		_spec.SetField(lotterydraw.FieldPrizeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeValue(); ok {
		_spec.SetField(lotterydraw.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrizeValue(); ok {
		_spec.AddField(lotterydraw.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RulesVersion(); ok {
		_spec.SetField(lotterydraw.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRulesVersion(); ok {
		_spec.AddField(lotterydraw.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(lotterydraw.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceSpentAtDraw(); ok {
		_spec.SetField(lotterydraw.FieldBalanceSpentAtDraw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceSpentAtDraw(); ok {
		_spec.AddField(lotterydraw.FieldBalanceSpentAtDraw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FulfillmentStatus(); ok {
		_spec.SetField(lotterydraw.FieldFulfillmentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FulfilledAt(); ok {
		_spec.SetField(lotterydraw.FieldFulfilledAt, field.TypeTime, value)
	}
	if _u.mutation.FulfilledAtCleared() {
		_spec.ClearField(lotterydraw.FieldFulfilledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FulfillmentError(); ok {
		_spec.SetField(lotterydraw.FieldFulfillmentError, field.TypeString, value)
	}
	if _u.mutation.FulfillmentErrorCleared() {
		_spec.ClearField(lotterydraw.FieldFulfillmentError, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(lotterydraw.FieldIdempotencyKey, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydraw.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryDrawUpdateOne is the builder for updating a single LotteryDraw entity.
type LotteryDrawUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryDrawMutation
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawUpdateOne) SetUserID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableUserID(v *int64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryDrawUpdateOne) AddUserID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryDrawUpdateOne) SetActivityID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.ResetActivityID()
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableActivityID(v *int64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// AddActivityID adds value to the "activity_id" field.
func (_u *LotteryDrawUpdateOne) AddActivityID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.AddActivityID(v)
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *LotteryDrawUpdateOne) SetPrizeID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.ResetPrizeID()
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillablePrizeID(v *int64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// AddPrizeID adds value to the "prize_id" field.
func (_u *LotteryDrawUpdateOne) AddPrizeID(v int64) *LotteryDrawUpdateOne {
	_u.mutation.AddPrizeID(v)
	return _u
}

// ClearPrizeID clears the value of the "prize_id" field.
func (_u *LotteryDrawUpdateOne) ClearPrizeID() *LotteryDrawUpdateOne {
	_u.mutation.ClearPrizeID()
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawUpdateOne) SetPrizeName(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillablePrizeName(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetPrizeType sets the "prize_type" field.
func (_u *LotteryDrawUpdateOne) SetPrizeType(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetPrizeType(v)
	return _u
}

// SetNillablePrizeType sets the "prize_type" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillablePrizeType(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetPrizeType(*v)
	}
	return _u
}

// SetPrizeValue sets the "prize_value" field.
func (_u *LotteryDrawUpdateOne) SetPrizeValue(v float64) *LotteryDrawUpdateOne {
	_u.mutation.ResetPrizeValue()
	_u.mutation.SetPrizeValue(v)
	return _u
}

// SetNillablePrizeValue sets the "prize_value" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillablePrizeValue(v *float64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetPrizeValue(*v)
	}
	return _u
}

// AddPrizeValue adds value to the "prize_value" field.
func (_u *LotteryDrawUpdateOne) AddPrizeValue(v float64) *LotteryDrawUpdateOne {
	_u.mutation.AddPrizeValue(v)
	return _u
}

// SetRulesVersion sets the "rules_version" field.
func (_u *LotteryDrawUpdateOne) SetRulesVersion(v int) *LotteryDrawUpdateOne {
	_u.mutation.ResetRulesVersion()
	_u.mutation.SetRulesVersion(v)
	return _u
}

// SetNillableRulesVersion sets the "rules_version" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableRulesVersion(v *int) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetRulesVersion(*v)
	}
	return _u
}

// AddRulesVersion adds value to the "rules_version" field.
func (_u *LotteryDrawUpdateOne) AddRulesVersion(v int) *LotteryDrawUpdateOne {
	_u.mutation.AddRulesVersion(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *LotteryDrawUpdateOne) SetSource(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableSource(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetBalanceSpentAtDraw sets the "balance_spent_at_draw" field.
func (_u *LotteryDrawUpdateOne) SetBalanceSpentAtDraw(v float64) *LotteryDrawUpdateOne {
	_u.mutation.ResetBalanceSpentAtDraw()
	_u.mutation.SetBalanceSpentAtDraw(v)
	return _u
}

// SetNillableBalanceSpentAtDraw sets the "balance_spent_at_draw" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableBalanceSpentAtDraw(v *float64) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetBalanceSpentAtDraw(*v)
	}
	return _u
}

// AddBalanceSpentAtDraw adds value to the "balance_spent_at_draw" field.
func (_u *LotteryDrawUpdateOne) AddBalanceSpentAtDraw(v float64) *LotteryDrawUpdateOne {
	_u.mutation.AddBalanceSpentAtDraw(v)
	return _u
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (_u *LotteryDrawUpdateOne) SetFulfillmentStatus(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetFulfillmentStatus(v)
	return _u
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableFulfillmentStatus(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetFulfillmentStatus(*v)
	}
	return _u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_u *LotteryDrawUpdateOne) SetFulfilledAt(v time.Time) *LotteryDrawUpdateOne {
	_u.mutation.SetFulfilledAt(v)
	return _u
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableFulfilledAt(v *time.Time) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetFulfilledAt(*v)
	}
	return _u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (_u *LotteryDrawUpdateOne) ClearFulfilledAt() *LotteryDrawUpdateOne {
	_u.mutation.ClearFulfilledAt()
	return _u
}

// SetFulfillmentError sets the "fulfillment_error" field.
func (_u *LotteryDrawUpdateOne) SetFulfillmentError(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetFulfillmentError(v)
	return _u
}

// SetNillableFulfillmentError sets the "fulfillment_error" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableFulfillmentError(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetFulfillmentError(*v)
	}
	return _u
}

// ClearFulfillmentError clears the value of the "fulfillment_error" field.
func (_u *LotteryDrawUpdateOne) ClearFulfillmentError() *LotteryDrawUpdateOne {
	_u.mutation.ClearFulfillmentError()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *LotteryDrawUpdateOne) SetIdempotencyKey(v string) *LotteryDrawUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *LotteryDrawUpdateOne) SetNillableIdempotencyKey(v *string) *LotteryDrawUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// Mutation returns the LotteryDrawMutation object of the builder.
func (_u *LotteryDrawUpdateOne) Mutation() *LotteryDrawMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryDrawUpdate builder.
func (_u *LotteryDrawUpdateOne) Where(ps ...predicate.LotteryDraw) *LotteryDrawUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryDrawUpdateOne) Select(field string, fields ...string) *LotteryDrawUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryDraw entity.
func (_u *LotteryDrawUpdateOne) Save(ctx context.Context) (*LotteryDraw, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawUpdateOne) SaveX(ctx context.Context) *LotteryDraw {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryDrawUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryDrawUpdateOne) check() error {
	if v, ok := _u.mutation.PrizeName(); ok {
		if err := lotterydraw.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeType(); ok {
		if err := lotterydraw.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := lotterydraw.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FulfillmentStatus(); ok {
		if err := lotterydraw.FulfillmentStatusValidator(v); err != nil {
			return &ValidationError{Name: "fulfillment_status", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.fulfillment_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := lotterydraw.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.idempotency_key": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryDrawUpdateOne) sqlSave(ctx context.Context) (_node *LotteryDraw, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterydraw.Table, lotterydraw.Columns, sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryDraw.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterydraw.FieldID)
		for _, f := range fields {
			if !lotterydraw.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterydraw.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterydraw.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(lotterydraw.FieldActivityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActivityID(); ok {
		_spec.AddField(lotterydraw.FieldActivityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeID(); ok {
		_spec.SetField(lotterydraw.FieldPrizeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizeID(); ok {
		_spec.AddField(lotterydraw.FieldPrizeID, field.TypeInt64, value)
	}
	if _u.mutation.PrizeIDCleared() {
		_spec.ClearField(lotterydraw.FieldPrizeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydraw.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeType(); ok {
		_spec.SetField(lotterydraw.FieldPrizeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeValue(); ok {
		_spec.SetField(lotterydraw.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrizeValue(); ok {
		_spec.AddField(lotterydraw.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RulesVersion(); ok {
		_spec.SetField(lotterydraw.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRulesVersion(); ok {
		_spec.AddField(lotterydraw.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(lotterydraw.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceSpentAtDraw(); ok {
		_spec.SetField(lotterydraw.FieldBalanceSpentAtDraw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceSpentAtDraw(); ok {
		_spec.AddField(lotterydraw.FieldBalanceSpentAtDraw, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FulfillmentStatus(); ok {
		_spec.SetField(lotterydraw.FieldFulfillmentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FulfilledAt(); ok {
		_spec.SetField(lotterydraw.FieldFulfilledAt, field.TypeTime, value)
	}
	if _u.mutation.FulfilledAtCleared() {
		_spec.ClearField(lotterydraw.FieldFulfilledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FulfillmentError(); ok {
		_spec.SetField(lotterydraw.FieldFulfillmentError, field.TypeString, value)
	}
	if _u.mutation.FulfillmentErrorCleared() {
		_spec.ClearField(lotterydraw.FieldFulfillmentError, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(lotterydraw.FieldIdempotencyKey, field.TypeString, value)
	}
	_node = &LotteryDraw{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydraw.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
