// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryuserstats"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryUserStatsDelete is the builder for deleting a LotteryUserStats entity.
type LotteryUserStatsDelete struct {
	config
	hooks    []Hook
	mutation *LotteryUserStatsMutation
}

// Where appends a list predicates to the LotteryUserStatsDelete builder.
func (_d *LotteryUserStatsDelete) Where(ps ...predicate.LotteryUserStats) *LotteryUserStatsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LotteryUserStatsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryUserStatsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LotteryUserStatsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(lotteryuserstats.Table, sqlgraph.NewFieldSpec(lotteryuserstats.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LotteryUserStatsDeleteOne is the builder for deleting a single LotteryUserStats entity.
type LotteryUserStatsDeleteOne struct {
	_d *LotteryUserStatsDelete
}

// Where appends a list predicates to the LotteryUserStatsDelete builder.
func (_d *LotteryUserStatsDeleteOne) Where(ps ...predicate.LotteryUserStats) *LotteryUserStatsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LotteryUserStatsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lotteryuserstats.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryUserStatsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
