// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
)

// LotteryPrizeCreate is the builder for creating a LotteryPrize entity.
type LotteryPrizeCreate struct {
	config
	mutation *LotteryPrizeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityID sets the "activity_id" field.
func (_c *LotteryPrizeCreate) SetActivityID(v int64) *LotteryPrizeCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *LotteryPrizeCreate) SetName(v string) *LotteryPrizeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPrizeType sets the "prize_type" field.
func (_c *LotteryPrizeCreate) SetPrizeType(v string) *LotteryPrizeCreate {
	_c.mutation.SetPrizeType(v)
	return _c
}

// SetNillablePrizeType sets the "prize_type" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillablePrizeType(v *string) *LotteryPrizeCreate {
	if v != nil {
		_c.SetPrizeType(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *LotteryPrizeCreate) SetValue(v float64) *LotteryPrizeCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableValue(v *float64) *LotteryPrizeCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *LotteryPrizeCreate) SetWeight(v int) *LotteryPrizeCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableWeight(v *int) *LotteryPrizeCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetMinTier sets the "min_tier" field.
func (_c *LotteryPrizeCreate) SetMinTier(v int) *LotteryPrizeCreate {
	_c.mutation.SetMinTier(v)
	return _c
}

// SetNillableMinTier sets the "min_tier" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableMinTier(v *int) *LotteryPrizeCreate {
	if v != nil {
		_c.SetMinTier(*v)
	}
	return _c
}

// SetTierWeights sets the "tier_weights" field.
func (_c *LotteryPrizeCreate) SetTierWeights(v map[string]int) *LotteryPrizeCreate {
	_c.mutation.SetTierWeights(v)
	return _c
}

// SetStock sets the "stock" field.
func (_c *LotteryPrizeCreate) SetStock(v int) *LotteryPrizeCreate {
	_c.mutation.SetStock(v)
	return _c
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableStock(v *int) *LotteryPrizeCreate {
	if v != nil {
		_c.SetStock(*v)
	}
	return _c
}

// SetStockIssued sets the "stock_issued" field.
func (_c *LotteryPrizeCreate) SetStockIssued(v int) *LotteryPrizeCreate {
	_c.mutation.SetStockIssued(v)
	return _c
}

// SetNillableStockIssued sets the "stock_issued" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableStockIssued(v *int) *LotteryPrizeCreate {
	if v != nil {
		_c.SetStockIssued(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *LotteryPrizeCreate) SetEnabled(v bool) *LotteryPrizeCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableEnabled(v *bool) *LotteryPrizeCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *LotteryPrizeCreate) SetSortOrder(v int) *LotteryPrizeCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableSortOrder(v *int) *LotteryPrizeCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryPrizeCreate) SetCreatedAt(v time.Time) *LotteryPrizeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableCreatedAt(v *time.Time) *LotteryPrizeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryPrizeCreate) SetUpdatedAt(v time.Time) *LotteryPrizeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryPrizeCreate) SetNillableUpdatedAt(v *time.Time) *LotteryPrizeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_c *LotteryPrizeCreate) SetActivity(v *LotteryActivity) *LotteryPrizeCreate {
	return _c.SetActivityID(v.ID)
}

// Mutation returns the LotteryPrizeMutation object of the builder.
func (_c *LotteryPrizeCreate) Mutation() *LotteryPrizeMutation {
	return _c.mutation
}

// Save creates the LotteryPrize in the database.
func (_c *LotteryPrizeCreate) Save(ctx context.Context) (*LotteryPrize, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryPrizeCreate) SaveX(ctx context.Context) *LotteryPrize {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryPrizeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryPrizeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryPrizeCreate) defaults() {
	if _, ok := _c.mutation.PrizeType(); !ok {
		v := lotteryprize.DefaultPrizeType
		_c.mutation.SetPrizeType(v)
	}
	if _, ok := _c.mutation.Value(); !ok {
		v := lotteryprize.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := lotteryprize.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.MinTier(); !ok {
		v := lotteryprize.DefaultMinTier
		_c.mutation.SetMinTier(v)
	}
	if _, ok := _c.mutation.Stock(); !ok {
		v := lotteryprize.DefaultStock
		_c.mutation.SetStock(v)
	}
	if _, ok := _c.mutation.StockIssued(); !ok {
		v := lotteryprize.DefaultStockIssued
		_c.mutation.SetStockIssued(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := lotteryprize.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := lotteryprize.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotteryprize.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotteryprize.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryPrizeCreate) check() error {
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "LotteryPrize.activity_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LotteryPrize.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := lotteryprize.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrizeType(); !ok {
		return &ValidationError{Name: "prize_type", err: errors.New(`ent: missing required field "LotteryPrize.prize_type"`)}
	}
	if v, ok := _c.mutation.PrizeType(); ok {
		if err := lotteryprize.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.prize_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "LotteryPrize.value"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "LotteryPrize.weight"`)}
	}
	if _, ok := _c.mutation.MinTier(); !ok {
		return &ValidationError{Name: "min_tier", err: errors.New(`ent: missing required field "LotteryPrize.min_tier"`)}
	}
	if _, ok := _c.mutation.Stock(); !ok {
		return &ValidationError{Name: "stock", err: errors.New(`ent: missing required field "LotteryPrize.stock"`)}
	}
	if _, ok := _c.mutation.StockIssued(); !ok {
		return &ValidationError{Name: "stock_issued", err: errors.New(`ent: missing required field "LotteryPrize.stock_issued"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "LotteryPrize.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "LotteryPrize.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryPrize.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryPrize.updated_at"`)}
	}
	if len(_c.mutation.ActivityIDs()) == 0 {
		return &ValidationError{Name: "activity", err: errors.New(`ent: missing required edge "LotteryPrize.activity"`)}
	}
	return nil
}

func (_c *LotteryPrizeCreate) sqlSave(ctx context.Context) (*LotteryPrize, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryPrizeCreate) createSpec() (*LotteryPrize, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryPrize{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryprize.Table, sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(lotteryprize.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.PrizeType(); ok {
		_spec.SetField(lotteryprize.FieldPrizeType, field.TypeString, value)
		_node.PrizeType = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(lotteryprize.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(lotteryprize.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.MinTier(); ok {
		_spec.SetField(lotteryprize.FieldMinTier, field.TypeInt, value)
		_node.MinTier = value
	}
	if value, ok := _c.mutation.TierWeights(); ok {
		_spec.SetField(lotteryprize.FieldTierWeights, field.TypeJSON, value)
		_node.TierWeights = value
	}
	if value, ok := _c.mutation.Stock(); ok {
		_spec.SetField(lotteryprize.FieldStock, field.TypeInt, value)
		_node.Stock = value
	}
	if value, ok := _c.mutation.StockIssued(); ok {
		_spec.SetField(lotteryprize.FieldStockIssued, field.TypeInt, value)
		_node.StockIssued = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(lotteryprize.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(lotteryprize.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryprize.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryprize.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.ActivityTable,
			Columns: []string{lotteryprize.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryPrize.Create().
//		SetActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryPrizeUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryPrizeCreate) OnConflict(opts ...sql.ConflictOption) *LotteryPrizeUpsertOne {
	_c.conflict = opts
	return &LotteryPrizeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryPrize.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryPrizeCreate) OnConflictColumns(columns ...string) *LotteryPrizeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryPrizeUpsertOne{
		create: _c,
	}
}

type (
	// LotteryPrizeUpsertOne is the builder for "upsert"-ing
	//  one LotteryPrize node.
	LotteryPrizeUpsertOne struct {
		create *LotteryPrizeCreate
	}

	// LotteryPrizeUpsert is the "OnConflict" setter.
	LotteryPrizeUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityID sets the "activity_id" field.
func (u *LotteryPrizeUpsert) SetActivityID(v int64) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateActivityID() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldActivityID)
	return u
}

// SetName sets the "name" field.
func (u *LotteryPrizeUpsert) SetName(v string) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateName() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldName)
	return u
}

// SetPrizeType sets the "prize_type" field.
func (u *LotteryPrizeUpsert) SetPrizeType(v string) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldPrizeType, v)
	return u
}

// UpdatePrizeType sets the "prize_type" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdatePrizeType() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldPrizeType)
	return u
}

// SetValue sets the "value" field.
func (u *LotteryPrizeUpsert) SetValue(v float64) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateValue() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldValue)
	return u
}

// AddValue adds v to the "value" field.
func (u *LotteryPrizeUpsert) AddValue(v float64) *LotteryPrizeUpsert {
	u.Add(lotteryprize.FieldValue, v)
	return u
}

// SetWeight sets the "weight" field.
func (u *LotteryPrizeUpsert) SetWeight(v int) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateWeight() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *LotteryPrizeUpsert) AddWeight(v int) *LotteryPrizeUpsert {
	u.Add(lotteryprize.FieldWeight, v)
	return u
}

// SetMinTier sets the "min_tier" field.
func (u *LotteryPrizeUpsert) SetMinTier(v int) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldMinTier, v)
	return u
}

// UpdateMinTier sets the "min_tier" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateMinTier() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldMinTier)
	return u
}

// AddMinTier adds v to the "min_tier" field.
func (u *LotteryPrizeUpsert) AddMinTier(v int) *LotteryPrizeUpsert {
	u.Add(lotteryprize.FieldMinTier, v)
	return u
}

// SetTierWeights sets the "tier_weights" field.
func (u *LotteryPrizeUpsert) SetTierWeights(v map[string]int) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldTierWeights, v)
	return u
}

// UpdateTierWeights sets the "tier_weights" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateTierWeights() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldTierWeights)
	return u
}

// ClearTierWeights clears the value of the "tier_weights" field.
func (u *LotteryPrizeUpsert) ClearTierWeights() *LotteryPrizeUpsert {
	u.SetNull(lotteryprize.FieldTierWeights)
	return u
}

// SetStock sets the "stock" field.
func (u *LotteryPrizeUpsert) SetStock(v int) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldStock, v)
	return u
}

// UpdateStock sets the "stock" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateStock() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldStock)
	return u
}

// AddStock adds v to the "stock" field.
func (u *LotteryPrizeUpsert) AddStock(v int) *LotteryPrizeUpsert {
	u.Add(lotteryprize.FieldStock, v)
	return u
}

// SetStockIssued sets the "stock_issued" field.
func (u *LotteryPrizeUpsert) SetStockIssued(v int) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldStockIssued, v)
	return u
}

// UpdateStockIssued sets the "stock_issued" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateStockIssued() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldStockIssued)
	return u
}

// AddStockIssued adds v to the "stock_issued" field.
func (u *LotteryPrizeUpsert) AddStockIssued(v int) *LotteryPrizeUpsert {
	u.Add(lotteryprize.FieldStockIssued, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *LotteryPrizeUpsert) SetEnabled(v bool) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateEnabled() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *LotteryPrizeUpsert) SetSortOrder(v int) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateSortOrder() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LotteryPrizeUpsert) AddSortOrder(v int) *LotteryPrizeUpsert {
	u.Add(lotteryprize.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryPrizeUpsert) SetUpdatedAt(v time.Time) *LotteryPrizeUpsert {
	u.Set(lotteryprize.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryPrizeUpsert) UpdateUpdatedAt() *LotteryPrizeUpsert {
	u.SetExcluded(lotteryprize.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryPrize.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryPrizeUpsertOne) UpdateNewValues() *LotteryPrizeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotteryprize.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryPrize.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryPrizeUpsertOne) Ignore() *LotteryPrizeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryPrizeUpsertOne) DoNothing() *LotteryPrizeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryPrizeCreate.OnConflict
// documentation for more info.
func (u *LotteryPrizeUpsertOne) Update(set func(*LotteryPrizeUpsert)) *LotteryPrizeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryPrizeUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryPrizeUpsertOne) SetActivityID(v int64) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateActivityID() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateActivityID()
	})
}

// SetName sets the "name" field.
func (u *LotteryPrizeUpsertOne) SetName(v string) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateName() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateName()
	})
}

// SetPrizeType sets the "prize_type" field.
func (u *LotteryPrizeUpsertOne) SetPrizeType(v string) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetPrizeType(v)
	})
}

// UpdatePrizeType sets the "prize_type" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdatePrizeType() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdatePrizeType()
	})
}

// SetValue sets the "value" field.
func (u *LotteryPrizeUpsertOne) SetValue(v float64) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *LotteryPrizeUpsertOne) AddValue(v float64) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateValue() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateValue()
	})
}

// SetWeight sets the "weight" field.
func (u *LotteryPrizeUpsertOne) SetWeight(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *LotteryPrizeUpsertOne) AddWeight(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateWeight() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateWeight()
	})
}

// SetMinTier sets the "min_tier" field.
func (u *LotteryPrizeUpsertOne) SetMinTier(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetMinTier(v)
	})
}

// AddMinTier adds v to the "min_tier" field.
func (u *LotteryPrizeUpsertOne) AddMinTier(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddMinTier(v)
	})
}

// UpdateMinTier sets the "min_tier" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateMinTier() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateMinTier()
	})
}

// SetTierWeights sets the "tier_weights" field.
func (u *LotteryPrizeUpsertOne) SetTierWeights(v map[string]int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetTierWeights(v)
	})
}

// UpdateTierWeights sets the "tier_weights" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateTierWeights() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateTierWeights()
	})
}

// ClearTierWeights clears the value of the "tier_weights" field.
func (u *LotteryPrizeUpsertOne) ClearTierWeights() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.ClearTierWeights()
	})
}

// SetStock sets the "stock" field.
func (u *LotteryPrizeUpsertOne) SetStock(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetStock(v)
	})
}

// AddStock adds v to the "stock" field.
func (u *LotteryPrizeUpsertOne) AddStock(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddStock(v)
	})
}

// UpdateStock sets the "stock" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateStock() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateStock()
	})
}

// SetStockIssued sets the "stock_issued" field.
func (u *LotteryPrizeUpsertOne) SetStockIssued(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetStockIssued(v)
	})
}

// AddStockIssued adds v to the "stock_issued" field.
func (u *LotteryPrizeUpsertOne) AddStockIssued(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddStockIssued(v)
	})
}

// UpdateStockIssued sets the "stock_issued" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateStockIssued() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateStockIssued()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LotteryPrizeUpsertOne) SetEnabled(v bool) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateEnabled() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LotteryPrizeUpsertOne) SetSortOrder(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LotteryPrizeUpsertOne) AddSortOrder(v int) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateSortOrder() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryPrizeUpsertOne) SetUpdatedAt(v time.Time) *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryPrizeUpsertOne) UpdateUpdatedAt() *LotteryPrizeUpsertOne {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryPrizeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryPrizeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryPrizeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryPrizeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryPrizeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryPrizeCreateBulk is the builder for creating many LotteryPrize entities in bulk.
type LotteryPrizeCreateBulk struct {
	config
	err      error
	builders []*LotteryPrizeCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryPrize entities in the database.
func (_c *LotteryPrizeCreateBulk) Save(ctx context.Context) ([]*LotteryPrize, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryPrize, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryPrizeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryPrizeCreateBulk) SaveX(ctx context.Context) []*LotteryPrize {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryPrizeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryPrizeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryPrize.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryPrizeUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryPrizeCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryPrizeUpsertBulk {
	_c.conflict = opts
	return &LotteryPrizeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryPrize.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryPrizeCreateBulk) OnConflictColumns(columns ...string) *LotteryPrizeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryPrizeUpsertBulk{
		create: _c,
	}
}

// LotteryPrizeUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryPrize nodes.
type LotteryPrizeUpsertBulk struct {
	create *LotteryPrizeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryPrize.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryPrizeUpsertBulk) UpdateNewValues() *LotteryPrizeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotteryprize.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryPrize.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryPrizeUpsertBulk) Ignore() *LotteryPrizeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryPrizeUpsertBulk) DoNothing() *LotteryPrizeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryPrizeCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryPrizeUpsertBulk) Update(set func(*LotteryPrizeUpsert)) *LotteryPrizeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryPrizeUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryPrizeUpsertBulk) SetActivityID(v int64) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateActivityID() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateActivityID()
	})
}

// SetName sets the "name" field.
func (u *LotteryPrizeUpsertBulk) SetName(v string) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateName() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateName()
	})
}

// SetPrizeType sets the "prize_type" field.
func (u *LotteryPrizeUpsertBulk) SetPrizeType(v string) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetPrizeType(v)
	})
}

// UpdatePrizeType sets the "prize_type" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdatePrizeType() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdatePrizeType()
	})
}

// SetValue sets the "value" field.
func (u *LotteryPrizeUpsertBulk) SetValue(v float64) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *LotteryPrizeUpsertBulk) AddValue(v float64) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateValue() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateValue()
	})
}

// SetWeight sets the "weight" field.
func (u *LotteryPrizeUpsertBulk) SetWeight(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *LotteryPrizeUpsertBulk) AddWeight(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateWeight() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateWeight()
	})
}

// SetMinTier sets the "min_tier" field.
func (u *LotteryPrizeUpsertBulk) SetMinTier(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetMinTier(v)
	})
}

// AddMinTier adds v to the "min_tier" field.
func (u *LotteryPrizeUpsertBulk) AddMinTier(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddMinTier(v)
	})
}

// UpdateMinTier sets the "min_tier" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateMinTier() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateMinTier()
	})
}

// SetTierWeights sets the "tier_weights" field.
func (u *LotteryPrizeUpsertBulk) SetTierWeights(v map[string]int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetTierWeights(v)
	})
}

// UpdateTierWeights sets the "tier_weights" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateTierWeights() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateTierWeights()
	})
}

// ClearTierWeights clears the value of the "tier_weights" field.
func (u *LotteryPrizeUpsertBulk) ClearTierWeights() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.ClearTierWeights()
	})
}

// SetStock sets the "stock" field.
func (u *LotteryPrizeUpsertBulk) SetStock(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetStock(v)
	})
}

// AddStock adds v to the "stock" field.
func (u *LotteryPrizeUpsertBulk) AddStock(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddStock(v)
	})
}

// UpdateStock sets the "stock" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateStock() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateStock()
	})
}

// SetStockIssued sets the "stock_issued" field.
func (u *LotteryPrizeUpsertBulk) SetStockIssued(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetStockIssued(v)
	})
}

// AddStockIssued adds v to the "stock_issued" field.
func (u *LotteryPrizeUpsertBulk) AddStockIssued(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddStockIssued(v)
	})
}

// UpdateStockIssued sets the "stock_issued" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateStockIssued() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateStockIssued()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LotteryPrizeUpsertBulk) SetEnabled(v bool) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateEnabled() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LotteryPrizeUpsertBulk) SetSortOrder(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LotteryPrizeUpsertBulk) AddSortOrder(v int) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateSortOrder() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryPrizeUpsertBulk) SetUpdatedAt(v time.Time) *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryPrizeUpsertBulk) UpdateUpdatedAt() *LotteryPrizeUpsertBulk {
	return u.Update(func(s *LotteryPrizeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryPrizeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryPrizeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryPrizeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryPrizeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
