// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
)

// LotteryDrawCreate is the builder for creating a LotteryDraw entity.
type LotteryDrawCreate struct {
	config
	mutation *LotteryDrawMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *LotteryDrawCreate) SetUserID(v int64) *LotteryDrawCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetActivityID sets the "activity_id" field.
func (_c *LotteryDrawCreate) SetActivityID(v int64) *LotteryDrawCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetPrizeID sets the "prize_id" field.
func (_c *LotteryDrawCreate) SetPrizeID(v int64) *LotteryDrawCreate {
	_c.mutation.SetPrizeID(v)
	return _c
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_c *LotteryDrawCreate) SetNillablePrizeID(v *int64) *LotteryDrawCreate {
	if v != nil {
		_c.SetPrizeID(*v)
	}
	return _c
}

// SetPrizeName sets the "prize_name" field.
func (_c *LotteryDrawCreate) SetPrizeName(v string) *LotteryDrawCreate {
	_c.mutation.SetPrizeName(v)
	return _c
}

// SetPrizeType sets the "prize_type" field.
func (_c *LotteryDrawCreate) SetPrizeType(v string) *LotteryDrawCreate {
	_c.mutation.SetPrizeType(v)
	return _c
}

// SetPrizeValue sets the "prize_value" field.
func (_c *LotteryDrawCreate) SetPrizeValue(v float64) *LotteryDrawCreate {
	_c.mutation.SetPrizeValue(v)
	return _c
}

// SetNillablePrizeValue sets the "prize_value" field if the given value is not nil.
func (_c *LotteryDrawCreate) SetNillablePrizeValue(v *float64) *LotteryDrawCreate {
	if v != nil {
		_c.SetPrizeValue(*v)
	}
	return _c
}

// SetRulesVersion sets the "rules_version" field.
func (_c *LotteryDrawCreate) SetRulesVersion(v int) *LotteryDrawCreate {
	_c.mutation.SetRulesVersion(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *LotteryDrawCreate) SetSource(v string) *LotteryDrawCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetBalanceSpentAtDraw sets the "balance_spent_at_draw" field.
func (_c *LotteryDrawCreate) SetBalanceSpentAtDraw(v float64) *LotteryDrawCreate {
	_c.mutation.SetBalanceSpentAtDraw(v)
	return _c
}

// SetNillableBalanceSpentAtDraw sets the "balance_spent_at_draw" field if the given value is not nil.
func (_c *LotteryDrawCreate) SetNillableBalanceSpentAtDraw(v *float64) *LotteryDrawCreate {
	if v != nil {
		_c.SetBalanceSpentAtDraw(*v)
	}
	return _c
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (_c *LotteryDrawCreate) SetFulfillmentStatus(v string) *LotteryDrawCreate {
	_c.mutation.SetFulfillmentStatus(v)
	return _c
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (_c *LotteryDrawCreate) SetNillableFulfillmentStatus(v *string) *LotteryDrawCreate {
	if v != nil {
		_c.SetFulfillmentStatus(*v)
	}
	return _c
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_c *LotteryDrawCreate) SetFulfilledAt(v time.Time) *LotteryDrawCreate {
	_c.mutation.SetFulfilledAt(v)
	return _c
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_c *LotteryDrawCreate) SetNillableFulfilledAt(v *time.Time) *LotteryDrawCreate {
	if v != nil {
		_c.SetFulfilledAt(*v)
	}
	return _c
}

// SetFulfillmentError sets the "fulfillment_error" field.
func (_c *LotteryDrawCreate) SetFulfillmentError(v string) *LotteryDrawCreate {
	_c.mutation.SetFulfillmentError(v)
	return _c
}

// SetNillableFulfillmentError sets the "fulfillment_error" field if the given value is not nil.
func (_c *LotteryDrawCreate) SetNillableFulfillmentError(v *string) *LotteryDrawCreate {
	if v != nil {
		_c.SetFulfillmentError(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *LotteryDrawCreate) SetIdempotencyKey(v string) *LotteryDrawCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryDrawCreate) SetCreatedAt(v time.Time) *LotteryDrawCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryDrawCreate) SetNillableCreatedAt(v *time.Time) *LotteryDrawCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LotteryDrawMutation object of the builder.
func (_c *LotteryDrawCreate) Mutation() *LotteryDrawMutation {
	return _c.mutation
}

// Save creates the LotteryDraw in the database.
func (_c *LotteryDrawCreate) Save(ctx context.Context) (*LotteryDraw, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryDrawCreate) SaveX(ctx context.Context) *LotteryDraw {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryDrawCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryDrawCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryDrawCreate) defaults() {
	if _, ok := _c.mutation.PrizeValue(); !ok {
		v := lotterydraw.DefaultPrizeValue
		_c.mutation.SetPrizeValue(v)
	}
	if _, ok := _c.mutation.BalanceSpentAtDraw(); !ok {
		v := lotterydraw.DefaultBalanceSpentAtDraw
		_c.mutation.SetBalanceSpentAtDraw(v)
	}
	if _, ok := _c.mutation.FulfillmentStatus(); !ok {
		v := lotterydraw.DefaultFulfillmentStatus
		_c.mutation.SetFulfillmentStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterydraw.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryDrawCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryDraw.user_id"`)}
	}
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "LotteryDraw.activity_id"`)}
	}
	if _, ok := _c.mutation.PrizeName(); !ok {
		return &ValidationError{Name: "prize_name", err: errors.New(`ent: missing required field "LotteryDraw.prize_name"`)}
	}
	if v, ok := _c.mutation.PrizeName(); ok {
		if err := lotterydraw.PrizeNameValidator(v); err != nil {
			return &ValidationError{Name: "prize_name", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrizeType(); !ok {
		return &ValidationError{Name: "prize_type", err: errors.New(`ent: missing required field "LotteryDraw.prize_type"`)}
	}
	if v, ok := _c.mutation.PrizeType(); ok {
		if err := lotterydraw.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.prize_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrizeValue(); !ok {
		return &ValidationError{Name: "prize_value", err: errors.New(`ent: missing required field "LotteryDraw.prize_value"`)}
	}
	if _, ok := _c.mutation.RulesVersion(); !ok {
		return &ValidationError{Name: "rules_version", err: errors.New(`ent: missing required field "LotteryDraw.rules_version"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "LotteryDraw.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := lotterydraw.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceSpentAtDraw(); !ok {
		return &ValidationError{Name: "balance_spent_at_draw", err: errors.New(`ent: missing required field "LotteryDraw.balance_spent_at_draw"`)}
	}
	if _, ok := _c.mutation.FulfillmentStatus(); !ok {
		return &ValidationError{Name: "fulfillment_status", err: errors.New(`ent: missing required field "LotteryDraw.fulfillment_status"`)}
	}
	if v, ok := _c.mutation.FulfillmentStatus(); ok {
		if err := lotterydraw.FulfillmentStatusValidator(v); err != nil {
			return &ValidationError{Name: "fulfillment_status", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.fulfillment_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "LotteryDraw.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := lotterydraw.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "LotteryDraw.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryDraw.created_at"`)}
	}
	return nil
}

func (_c *LotteryDrawCreate) sqlSave(ctx context.Context) (*LotteryDraw, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryDrawCreate) createSpec() (*LotteryDraw, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryDraw{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterydraw.Table, sqlgraph.NewFieldSpec(lotterydraw.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotterydraw.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ActivityID(); ok {
		_spec.SetField(lotterydraw.FieldActivityID, field.TypeInt64, value)
		_node.ActivityID = value
	}
	if value, ok := _c.mutation.PrizeID(); ok {
		_spec.SetField(lotterydraw.FieldPrizeID, field.TypeInt64, value)
		_node.PrizeID = &value
	}
	if value, ok := _c.mutation.PrizeName(); ok {
		_spec.SetField(lotterydraw.FieldPrizeName, field.TypeString, value)
		_node.PrizeName = value
	}
	if value, ok := _c.mutation.PrizeType(); ok {
		_spec.SetField(lotterydraw.FieldPrizeType, field.TypeString, value)
		_node.PrizeType = value
	}
	if value, ok := _c.mutation.PrizeValue(); ok {
		_spec.SetField(lotterydraw.FieldPrizeValue, field.TypeFloat64, value)
		_node.PrizeValue = value
	}
	if value, ok := _c.mutation.RulesVersion(); ok {
		_spec.SetField(lotterydraw.FieldRulesVersion, field.TypeInt, value)
		_node.RulesVersion = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(lotterydraw.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.BalanceSpentAtDraw(); ok {
		_spec.SetField(lotterydraw.FieldBalanceSpentAtDraw, field.TypeFloat64, value)
		_node.BalanceSpentAtDraw = value
	}
	if value, ok := _c.mutation.FulfillmentStatus(); ok {
		_spec.SetField(lotterydraw.FieldFulfillmentStatus, field.TypeString, value)
		_node.FulfillmentStatus = value
	}
	if value, ok := _c.mutation.FulfilledAt(); ok {
		_spec.SetField(lotterydraw.FieldFulfilledAt, field.TypeTime, value)
		_node.FulfilledAt = &value
	}
	if value, ok := _c.mutation.FulfillmentError(); ok {
		_spec.SetField(lotterydraw.FieldFulfillmentError, field.TypeString, value)
		_node.FulfillmentError = &value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(lotterydraw.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterydraw.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryDraw.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryDrawUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryDrawCreate) OnConflict(opts ...sql.ConflictOption) *LotteryDrawUpsertOne {
	_c.conflict = opts
	return &LotteryDrawUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryDraw.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryDrawCreate) OnConflictColumns(columns ...string) *LotteryDrawUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryDrawUpsertOne{
		create: _c,
	}
}

type (
	// LotteryDrawUpsertOne is the builder for "upsert"-ing
	//  one LotteryDraw node.
	LotteryDrawUpsertOne struct {
		create *LotteryDrawCreate
	}

	// LotteryDrawUpsert is the "OnConflict" setter.
	LotteryDrawUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *LotteryDrawUpsert) SetUserID(v int64) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateUserID() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryDrawUpsert) AddUserID(v int64) *LotteryDrawUpsert {
	u.Add(lotterydraw.FieldUserID, v)
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryDrawUpsert) SetActivityID(v int64) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateActivityID() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldActivityID)
	return u
}

// AddActivityID adds v to the "activity_id" field.
func (u *LotteryDrawUpsert) AddActivityID(v int64) *LotteryDrawUpsert {
	u.Add(lotterydraw.FieldActivityID, v)
	return u
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryDrawUpsert) SetPrizeID(v int64) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldPrizeID, v)
	return u
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdatePrizeID() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldPrizeID)
	return u
}

// AddPrizeID adds v to the "prize_id" field.
func (u *LotteryDrawUpsert) AddPrizeID(v int64) *LotteryDrawUpsert {
	u.Add(lotterydraw.FieldPrizeID, v)
	return u
}

// ClearPrizeID clears the value of the "prize_id" field.
func (u *LotteryDrawUpsert) ClearPrizeID() *LotteryDrawUpsert {
	u.SetNull(lotterydraw.FieldPrizeID)
	return u
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawUpsert) SetPrizeName(v string) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldPrizeName, v)
	return u
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdatePrizeName() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldPrizeName)
	return u
}

// SetPrizeType sets the "prize_type" field.
func (u *LotteryDrawUpsert) SetPrizeType(v string) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldPrizeType, v)
	return u
}

// UpdatePrizeType sets the "prize_type" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdatePrizeType() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldPrizeType)
	return u
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryDrawUpsert) SetPrizeValue(v float64) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldPrizeValue, v)
	return u
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdatePrizeValue() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldPrizeValue)
	return u
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryDrawUpsert) AddPrizeValue(v float64) *LotteryDrawUpsert {
	u.Add(lotterydraw.FieldPrizeValue, v)
	return u
}

// SetRulesVersion sets the "rules_version" field.
func (u *LotteryDrawUpsert) SetRulesVersion(v int) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldRulesVersion, v)
	return u
}

// UpdateRulesVersion sets the "rules_version" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateRulesVersion() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldRulesVersion)
	return u
}

// AddRulesVersion adds v to the "rules_version" field.
func (u *LotteryDrawUpsert) AddRulesVersion(v int) *LotteryDrawUpsert {
	u.Add(lotterydraw.FieldRulesVersion, v)
	return u
}

// SetSource sets the "source" field.
func (u *LotteryDrawUpsert) SetSource(v string) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateSource() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldSource)
	return u
}

// SetBalanceSpentAtDraw sets the "balance_spent_at_draw" field.
func (u *LotteryDrawUpsert) SetBalanceSpentAtDraw(v float64) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldBalanceSpentAtDraw, v)
	return u
}

// UpdateBalanceSpentAtDraw sets the "balance_spent_at_draw" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateBalanceSpentAtDraw() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldBalanceSpentAtDraw)
	return u
}

// AddBalanceSpentAtDraw adds v to the "balance_spent_at_draw" field.
func (u *LotteryDrawUpsert) AddBalanceSpentAtDraw(v float64) *LotteryDrawUpsert {
	u.Add(lotterydraw.FieldBalanceSpentAtDraw, v)
	return u
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (u *LotteryDrawUpsert) SetFulfillmentStatus(v string) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldFulfillmentStatus, v)
	return u
}

// UpdateFulfillmentStatus sets the "fulfillment_status" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateFulfillmentStatus() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldFulfillmentStatus)
	return u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (u *LotteryDrawUpsert) SetFulfilledAt(v time.Time) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldFulfilledAt, v)
	return u
}

// UpdateFulfilledAt sets the "fulfilled_at" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateFulfilledAt() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldFulfilledAt)
	return u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (u *LotteryDrawUpsert) ClearFulfilledAt() *LotteryDrawUpsert {
	u.SetNull(lotterydraw.FieldFulfilledAt)
	return u
}

// SetFulfillmentError sets the "fulfillment_error" field.
func (u *LotteryDrawUpsert) SetFulfillmentError(v string) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldFulfillmentError, v)
	return u
}

// UpdateFulfillmentError sets the "fulfillment_error" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateFulfillmentError() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldFulfillmentError)
	return u
}

// ClearFulfillmentError clears the value of the "fulfillment_error" field.
func (u *LotteryDrawUpsert) ClearFulfillmentError() *LotteryDrawUpsert {
	u.SetNull(lotterydraw.FieldFulfillmentError)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *LotteryDrawUpsert) SetIdempotencyKey(v string) *LotteryDrawUpsert {
	u.Set(lotterydraw.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *LotteryDrawUpsert) UpdateIdempotencyKey() *LotteryDrawUpsert {
	u.SetExcluded(lotterydraw.FieldIdempotencyKey)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryDraw.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryDrawUpsertOne) UpdateNewValues() *LotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterydraw.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryDraw.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryDrawUpsertOne) Ignore() *LotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryDrawUpsertOne) DoNothing() *LotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryDrawCreate.OnConflict
// documentation for more info.
func (u *LotteryDrawUpsertOne) Update(set func(*LotteryDrawUpsert)) *LotteryDrawUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryDrawUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryDrawUpsertOne) SetUserID(v int64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryDrawUpsertOne) AddUserID(v int64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateUserID() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateUserID()
	})
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryDrawUpsertOne) SetActivityID(v int64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetActivityID(v)
	})
}

// AddActivityID adds v to the "activity_id" field.
func (u *LotteryDrawUpsertOne) AddActivityID(v int64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateActivityID() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateActivityID()
	})
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryDrawUpsertOne) SetPrizeID(v int64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeID(v)
	})
}

// AddPrizeID adds v to the "prize_id" field.
func (u *LotteryDrawUpsertOne) AddPrizeID(v int64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddPrizeID(v)
	})
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdatePrizeID() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeID()
	})
}

// ClearPrizeID clears the value of the "prize_id" field.
func (u *LotteryDrawUpsertOne) ClearPrizeID() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.ClearPrizeID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawUpsertOne) SetPrizeName(v string) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdatePrizeName() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeName()
	})
}

// SetPrizeType sets the "prize_type" field.
func (u *LotteryDrawUpsertOne) SetPrizeType(v string) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeType(v)
	})
}

// UpdatePrizeType sets the "prize_type" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdatePrizeType() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeType()
	})
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryDrawUpsertOne) SetPrizeValue(v float64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeValue(v)
	})
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryDrawUpsertOne) AddPrizeValue(v float64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddPrizeValue(v)
	})
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdatePrizeValue() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeValue()
	})
}

// SetRulesVersion sets the "rules_version" field.
func (u *LotteryDrawUpsertOne) SetRulesVersion(v int) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetRulesVersion(v)
	})
}

// AddRulesVersion adds v to the "rules_version" field.
func (u *LotteryDrawUpsertOne) AddRulesVersion(v int) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddRulesVersion(v)
	})
}

// UpdateRulesVersion sets the "rules_version" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateRulesVersion() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateRulesVersion()
	})
}

// SetSource sets the "source" field.
func (u *LotteryDrawUpsertOne) SetSource(v string) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateSource() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateSource()
	})
}

// SetBalanceSpentAtDraw sets the "balance_spent_at_draw" field.
func (u *LotteryDrawUpsertOne) SetBalanceSpentAtDraw(v float64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetBalanceSpentAtDraw(v)
	})
}

// AddBalanceSpentAtDraw adds v to the "balance_spent_at_draw" field.
func (u *LotteryDrawUpsertOne) AddBalanceSpentAtDraw(v float64) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddBalanceSpentAtDraw(v)
	})
}

// UpdateBalanceSpentAtDraw sets the "balance_spent_at_draw" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateBalanceSpentAtDraw() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateBalanceSpentAtDraw()
	})
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (u *LotteryDrawUpsertOne) SetFulfillmentStatus(v string) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetFulfillmentStatus(v)
	})
}

// UpdateFulfillmentStatus sets the "fulfillment_status" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateFulfillmentStatus() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateFulfillmentStatus()
	})
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (u *LotteryDrawUpsertOne) SetFulfilledAt(v time.Time) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetFulfilledAt(v)
	})
}

// UpdateFulfilledAt sets the "fulfilled_at" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateFulfilledAt() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateFulfilledAt()
	})
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (u *LotteryDrawUpsertOne) ClearFulfilledAt() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.ClearFulfilledAt()
	})
}

// SetFulfillmentError sets the "fulfillment_error" field.
func (u *LotteryDrawUpsertOne) SetFulfillmentError(v string) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetFulfillmentError(v)
	})
}

// UpdateFulfillmentError sets the "fulfillment_error" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateFulfillmentError() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateFulfillmentError()
	})
}

// ClearFulfillmentError clears the value of the "fulfillment_error" field.
func (u *LotteryDrawUpsertOne) ClearFulfillmentError() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.ClearFulfillmentError()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *LotteryDrawUpsertOne) SetIdempotencyKey(v string) *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *LotteryDrawUpsertOne) UpdateIdempotencyKey() *LotteryDrawUpsertOne {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// Exec executes the query.
func (u *LotteryDrawUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryDrawCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryDrawUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryDrawUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryDrawUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryDrawCreateBulk is the builder for creating many LotteryDraw entities in bulk.
type LotteryDrawCreateBulk struct {
	config
	err      error
	builders []*LotteryDrawCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryDraw entities in the database.
func (_c *LotteryDrawCreateBulk) Save(ctx context.Context) ([]*LotteryDraw, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryDraw, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryDrawMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryDrawCreateBulk) SaveX(ctx context.Context) []*LotteryDraw {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryDrawCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryDrawCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryDraw.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryDrawUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryDrawCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryDrawUpsertBulk {
	_c.conflict = opts
	return &LotteryDrawUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryDraw.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryDrawCreateBulk) OnConflictColumns(columns ...string) *LotteryDrawUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryDrawUpsertBulk{
		create: _c,
	}
}

// LotteryDrawUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryDraw nodes.
type LotteryDrawUpsertBulk struct {
	create *LotteryDrawCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryDraw.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryDrawUpsertBulk) UpdateNewValues() *LotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterydraw.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryDraw.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryDrawUpsertBulk) Ignore() *LotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryDrawUpsertBulk) DoNothing() *LotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryDrawCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryDrawUpsertBulk) Update(set func(*LotteryDrawUpsert)) *LotteryDrawUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryDrawUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryDrawUpsertBulk) SetUserID(v int64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryDrawUpsertBulk) AddUserID(v int64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateUserID() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateUserID()
	})
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryDrawUpsertBulk) SetActivityID(v int64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetActivityID(v)
	})
}

// AddActivityID adds v to the "activity_id" field.
func (u *LotteryDrawUpsertBulk) AddActivityID(v int64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateActivityID() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateActivityID()
	})
}

// SetPrizeID sets the "prize_id" field.
func (u *LotteryDrawUpsertBulk) SetPrizeID(v int64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeID(v)
	})
}

// AddPrizeID adds v to the "prize_id" field.
func (u *LotteryDrawUpsertBulk) AddPrizeID(v int64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddPrizeID(v)
	})
}

// UpdatePrizeID sets the "prize_id" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdatePrizeID() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeID()
	})
}

// ClearPrizeID clears the value of the "prize_id" field.
func (u *LotteryDrawUpsertBulk) ClearPrizeID() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.ClearPrizeID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawUpsertBulk) SetPrizeName(v string) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdatePrizeName() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeName()
	})
}

// SetPrizeType sets the "prize_type" field.
func (u *LotteryDrawUpsertBulk) SetPrizeType(v string) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeType(v)
	})
}

// UpdatePrizeType sets the "prize_type" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdatePrizeType() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeType()
	})
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryDrawUpsertBulk) SetPrizeValue(v float64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetPrizeValue(v)
	})
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryDrawUpsertBulk) AddPrizeValue(v float64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddPrizeValue(v)
	})
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdatePrizeValue() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdatePrizeValue()
	})
}

// SetRulesVersion sets the "rules_version" field.
func (u *LotteryDrawUpsertBulk) SetRulesVersion(v int) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetRulesVersion(v)
	})
}

// AddRulesVersion adds v to the "rules_version" field.
func (u *LotteryDrawUpsertBulk) AddRulesVersion(v int) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddRulesVersion(v)
	})
}

// UpdateRulesVersion sets the "rules_version" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateRulesVersion() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateRulesVersion()
	})
}

// SetSource sets the "source" field.
func (u *LotteryDrawUpsertBulk) SetSource(v string) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateSource() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateSource()
	})
}

// SetBalanceSpentAtDraw sets the "balance_spent_at_draw" field.
func (u *LotteryDrawUpsertBulk) SetBalanceSpentAtDraw(v float64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetBalanceSpentAtDraw(v)
	})
}

// AddBalanceSpentAtDraw adds v to the "balance_spent_at_draw" field.
func (u *LotteryDrawUpsertBulk) AddBalanceSpentAtDraw(v float64) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.AddBalanceSpentAtDraw(v)
	})
}

// UpdateBalanceSpentAtDraw sets the "balance_spent_at_draw" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateBalanceSpentAtDraw() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateBalanceSpentAtDraw()
	})
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (u *LotteryDrawUpsertBulk) SetFulfillmentStatus(v string) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetFulfillmentStatus(v)
	})
}

// UpdateFulfillmentStatus sets the "fulfillment_status" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateFulfillmentStatus() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateFulfillmentStatus()
	})
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (u *LotteryDrawUpsertBulk) SetFulfilledAt(v time.Time) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetFulfilledAt(v)
	})
}

// UpdateFulfilledAt sets the "fulfilled_at" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateFulfilledAt() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateFulfilledAt()
	})
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (u *LotteryDrawUpsertBulk) ClearFulfilledAt() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.ClearFulfilledAt()
	})
}

// SetFulfillmentError sets the "fulfillment_error" field.
func (u *LotteryDrawUpsertBulk) SetFulfillmentError(v string) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetFulfillmentError(v)
	})
}

// UpdateFulfillmentError sets the "fulfillment_error" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateFulfillmentError() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateFulfillmentError()
	})
}

// ClearFulfillmentError clears the value of the "fulfillment_error" field.
func (u *LotteryDrawUpsertBulk) ClearFulfillmentError() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.ClearFulfillmentError()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *LotteryDrawUpsertBulk) SetIdempotencyKey(v string) *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *LotteryDrawUpsertBulk) UpdateIdempotencyKey() *LotteryDrawUpsertBulk {
	return u.Update(func(s *LotteryDrawUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// Exec executes the query.
func (u *LotteryDrawUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryDrawCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryDrawCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryDrawUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
