// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
)

// LotteryActivityCreate is the builder for creating a LotteryActivity entity.
type LotteryActivityCreate struct {
	config
	mutation *LotteryActivityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *LotteryActivityCreate) SetName(v string) *LotteryActivityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryActivityCreate) SetStatus(v string) *LotteryActivityCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableStatus(v *string) *LotteryActivityCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRulesVersion sets the "rules_version" field.
func (_c *LotteryActivityCreate) SetRulesVersion(v int) *LotteryActivityCreate {
	_c.mutation.SetRulesVersion(v)
	return _c
}

// SetNillableRulesVersion sets the "rules_version" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableRulesVersion(v *int) *LotteryActivityCreate {
	if v != nil {
		_c.SetRulesVersion(*v)
	}
	return _c
}

// SetTierMode sets the "tier_mode" field.
func (_c *LotteryActivityCreate) SetTierMode(v string) *LotteryActivityCreate {
	_c.mutation.SetTierMode(v)
	return _c
}

// SetNillableTierMode sets the "tier_mode" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableTierMode(v *string) *LotteryActivityCreate {
	if v != nil {
		_c.SetTierMode(*v)
	}
	return _c
}

// SetTierThresholds sets the "tier_thresholds" field.
func (_c *LotteryActivityCreate) SetTierThresholds(v []int64) *LotteryActivityCreate {
	_c.mutation.SetTierThresholds(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *LotteryActivityCreate) SetStartsAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableStartsAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *LotteryActivityCreate) SetEndsAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableEndsAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryActivityCreate) SetCreatedAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableCreatedAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryActivityCreate) SetUpdatedAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableUpdatedAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddPrizeIDs adds the "prizes" edge to the LotteryPrize entity by IDs.
func (_c *LotteryActivityCreate) AddPrizeIDs(ids ...int64) *LotteryActivityCreate {
	_c.mutation.AddPrizeIDs(ids...)
	return _c
}

// AddPrizes adds the "prizes" edges to the LotteryPrize entity.
func (_c *LotteryActivityCreate) AddPrizes(v ...*LotteryPrize) *LotteryActivityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPrizeIDs(ids...)
}

// Mutation returns the LotteryActivityMutation object of the builder.
func (_c *LotteryActivityCreate) Mutation() *LotteryActivityMutation {
	return _c.mutation
}

// Save creates the LotteryActivity in the database.
func (_c *LotteryActivityCreate) Save(ctx context.Context) (*LotteryActivity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryActivityCreate) SaveX(ctx context.Context) *LotteryActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryActivityCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := lotteryactivity.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RulesVersion(); !ok {
		v := lotteryactivity.DefaultRulesVersion
		_c.mutation.SetRulesVersion(v)
	}
	if _, ok := _c.mutation.TierMode(); !ok {
		v := lotteryactivity.DefaultTierMode
		_c.mutation.SetTierMode(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotteryactivity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotteryactivity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryActivityCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LotteryActivity.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := lotteryactivity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryActivity.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := lotteryactivity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RulesVersion(); !ok {
		return &ValidationError{Name: "rules_version", err: errors.New(`ent: missing required field "LotteryActivity.rules_version"`)}
	}
	if _, ok := _c.mutation.TierMode(); !ok {
		return &ValidationError{Name: "tier_mode", err: errors.New(`ent: missing required field "LotteryActivity.tier_mode"`)}
	}
	if v, ok := _c.mutation.TierMode(); ok {
		if err := lotteryactivity.TierModeValidator(v); err != nil {
			return &ValidationError{Name: "tier_mode", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.tier_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryActivity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryActivity.updated_at"`)}
	}
	return nil
}

func (_c *LotteryActivityCreate) sqlSave(ctx context.Context) (*LotteryActivity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryActivityCreate) createSpec() (*LotteryActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryActivity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryactivity.Table, sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(lotteryactivity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotteryactivity.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RulesVersion(); ok {
		_spec.SetField(lotteryactivity.FieldRulesVersion, field.TypeInt, value)
		_node.RulesVersion = value
	}
	if value, ok := _c.mutation.TierMode(); ok {
		_spec.SetField(lotteryactivity.FieldTierMode, field.TypeString, value)
		_node.TierMode = value
	}
	if value, ok := _c.mutation.TierThresholds(); ok {
		_spec.SetField(lotteryactivity.FieldTierThresholds, field.TypeJSON, value)
		_node.TierThresholds = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(lotteryactivity.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(lotteryactivity.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PrizesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.PrizesTable,
			Columns: []string{lotteryactivity.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryActivity.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryActivityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryActivityCreate) OnConflict(opts ...sql.ConflictOption) *LotteryActivityUpsertOne {
	_c.conflict = opts
	return &LotteryActivityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryActivityCreate) OnConflictColumns(columns ...string) *LotteryActivityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryActivityUpsertOne{
		create: _c,
	}
}

type (
	// LotteryActivityUpsertOne is the builder for "upsert"-ing
	//  one LotteryActivity node.
	LotteryActivityUpsertOne struct {
		create *LotteryActivityCreate
	}

	// LotteryActivityUpsert is the "OnConflict" setter.
	LotteryActivityUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *LotteryActivityUpsert) SetName(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateName() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryActivityUpsert) SetStatus(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateStatus() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldStatus)
	return u
}

// SetRulesVersion sets the "rules_version" field.
func (u *LotteryActivityUpsert) SetRulesVersion(v int) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldRulesVersion, v)
	return u
}

// UpdateRulesVersion sets the "rules_version" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateRulesVersion() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldRulesVersion)
	return u
}

// AddRulesVersion adds v to the "rules_version" field.
func (u *LotteryActivityUpsert) AddRulesVersion(v int) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldRulesVersion, v)
	return u
}

// SetTierMode sets the "tier_mode" field.
func (u *LotteryActivityUpsert) SetTierMode(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldTierMode, v)
	return u
}

// UpdateTierMode sets the "tier_mode" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateTierMode() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldTierMode)
	return u
}

// SetTierThresholds sets the "tier_thresholds" field.
func (u *LotteryActivityUpsert) SetTierThresholds(v []int64) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldTierThresholds, v)
	return u
}

// UpdateTierThresholds sets the "tier_thresholds" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateTierThresholds() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldTierThresholds)
	return u
}

// ClearTierThresholds clears the value of the "tier_thresholds" field.
func (u *LotteryActivityUpsert) ClearTierThresholds() *LotteryActivityUpsert {
	u.SetNull(lotteryactivity.FieldTierThresholds)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *LotteryActivityUpsert) SetStartsAt(v time.Time) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateStartsAt() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldStartsAt)
	return u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *LotteryActivityUpsert) ClearStartsAt() *LotteryActivityUpsert {
	u.SetNull(lotteryactivity.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *LotteryActivityUpsert) SetEndsAt(v time.Time) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateEndsAt() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldEndsAt)
	return u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *LotteryActivityUpsert) ClearEndsAt() *LotteryActivityUpsert {
	u.SetNull(lotteryactivity.FieldEndsAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryActivityUpsert) SetUpdatedAt(v time.Time) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateUpdatedAt() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryActivityUpsertOne) UpdateNewValues() *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotteryactivity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryActivityUpsertOne) Ignore() *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryActivityUpsertOne) DoNothing() *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryActivityCreate.OnConflict
// documentation for more info.
func (u *LotteryActivityUpsertOne) Update(set func(*LotteryActivityUpsert)) *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LotteryActivityUpsertOne) SetName(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateName() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryActivityUpsertOne) SetStatus(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateStatus() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateStatus()
	})
}

// SetRulesVersion sets the "rules_version" field.
func (u *LotteryActivityUpsertOne) SetRulesVersion(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetRulesVersion(v)
	})
}

// AddRulesVersion adds v to the "rules_version" field.
func (u *LotteryActivityUpsertOne) AddRulesVersion(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddRulesVersion(v)
	})
}

// UpdateRulesVersion sets the "rules_version" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateRulesVersion() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateRulesVersion()
	})
}

// SetTierMode sets the "tier_mode" field.
func (u *LotteryActivityUpsertOne) SetTierMode(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTierMode(v)
	})
}

// UpdateTierMode sets the "tier_mode" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateTierMode() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTierMode()
	})
}

// SetTierThresholds sets the "tier_thresholds" field.
func (u *LotteryActivityUpsertOne) SetTierThresholds(v []int64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTierThresholds(v)
	})
}

// UpdateTierThresholds sets the "tier_thresholds" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateTierThresholds() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTierThresholds()
	})
}

// ClearTierThresholds clears the value of the "tier_thresholds" field.
func (u *LotteryActivityUpsertOne) ClearTierThresholds() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearTierThresholds()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *LotteryActivityUpsertOne) SetStartsAt(v time.Time) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateStartsAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *LotteryActivityUpsertOne) ClearStartsAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *LotteryActivityUpsertOne) SetEndsAt(v time.Time) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateEndsAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *LotteryActivityUpsertOne) ClearEndsAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearEndsAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryActivityUpsertOne) SetUpdatedAt(v time.Time) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateUpdatedAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryActivityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryActivityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryActivityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryActivityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryActivityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryActivityCreateBulk is the builder for creating many LotteryActivity entities in bulk.
type LotteryActivityCreateBulk struct {
	config
	err      error
	builders []*LotteryActivityCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryActivity entities in the database.
func (_c *LotteryActivityCreateBulk) Save(ctx context.Context) ([]*LotteryActivity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryActivity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryActivityCreateBulk) SaveX(ctx context.Context) []*LotteryActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryActivity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryActivityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryActivityCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryActivityUpsertBulk {
	_c.conflict = opts
	return &LotteryActivityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryActivityCreateBulk) OnConflictColumns(columns ...string) *LotteryActivityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryActivityUpsertBulk{
		create: _c,
	}
}

// LotteryActivityUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryActivity nodes.
type LotteryActivityUpsertBulk struct {
	create *LotteryActivityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryActivityUpsertBulk) UpdateNewValues() *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotteryactivity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryActivityUpsertBulk) Ignore() *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryActivityUpsertBulk) DoNothing() *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryActivityCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryActivityUpsertBulk) Update(set func(*LotteryActivityUpsert)) *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LotteryActivityUpsertBulk) SetName(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateName() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryActivityUpsertBulk) SetStatus(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateStatus() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateStatus()
	})
}

// SetRulesVersion sets the "rules_version" field.
func (u *LotteryActivityUpsertBulk) SetRulesVersion(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetRulesVersion(v)
	})
}

// AddRulesVersion adds v to the "rules_version" field.
func (u *LotteryActivityUpsertBulk) AddRulesVersion(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddRulesVersion(v)
	})
}

// UpdateRulesVersion sets the "rules_version" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateRulesVersion() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateRulesVersion()
	})
}

// SetTierMode sets the "tier_mode" field.
func (u *LotteryActivityUpsertBulk) SetTierMode(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTierMode(v)
	})
}

// UpdateTierMode sets the "tier_mode" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateTierMode() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTierMode()
	})
}

// SetTierThresholds sets the "tier_thresholds" field.
func (u *LotteryActivityUpsertBulk) SetTierThresholds(v []int64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTierThresholds(v)
	})
}

// UpdateTierThresholds sets the "tier_thresholds" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateTierThresholds() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTierThresholds()
	})
}

// ClearTierThresholds clears the value of the "tier_thresholds" field.
func (u *LotteryActivityUpsertBulk) ClearTierThresholds() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearTierThresholds()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *LotteryActivityUpsertBulk) SetStartsAt(v time.Time) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateStartsAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *LotteryActivityUpsertBulk) ClearStartsAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *LotteryActivityUpsertBulk) SetEndsAt(v time.Time) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateEndsAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *LotteryActivityUpsertBulk) ClearEndsAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearEndsAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryActivityUpsertBulk) SetUpdatedAt(v time.Time) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateUpdatedAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryActivityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryActivityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryActivityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryActivityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
