// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
)

// LotteryDraw is the model entity for the LotteryDraw schema.
type LotteryDraw struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 活动 ID
	ActivityID int64 `json:"activity_id,omitempty"`
	// 奖品 ID，null 仅在异常兜底时出现
	PrizeID *int64 `json:"prize_id,omitempty"`
	// 奖品名称快照
	PrizeName string `json:"prize_name,omitempty"`
	// 奖品类型快照: none, balance_bonus, quota
	PrizeType string `json:"prize_type,omitempty"`
	// 奖品数值快照
	PrizeValue float64 `json:"prize_value,omitempty"`
	// 抽奖时的规则版本
	RulesVersion int `json:"rules_version,omitempty"`
	// 次数来源: first, threshold, manual
	Source string `json:"source,omitempty"`
	// 抽奖时的基线后累计余额消耗快照
	BalanceSpentAtDraw float64 `json:"balance_spent_at_draw,omitempty"`
	// 发放状态: pending, granted, failed
	FulfillmentStatus string `json:"fulfillment_status,omitempty"`
	// 发放完成时间
	FulfilledAt *time.Time `json:"fulfilled_at,omitempty"`
	// 发放失败原因
	FulfillmentError *string `json:"fulfillment_error,omitempty"`
	// 客户端幂等键
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryDraw) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterydraw.FieldPrizeValue, lotterydraw.FieldBalanceSpentAtDraw:
			values[i] = new(sql.NullFloat64)
		case lotterydraw.FieldID, lotterydraw.FieldUserID, lotterydraw.FieldActivityID, lotterydraw.FieldPrizeID, lotterydraw.FieldRulesVersion:
			values[i] = new(sql.NullInt64)
		case lotterydraw.FieldPrizeName, lotterydraw.FieldPrizeType, lotterydraw.FieldSource, lotterydraw.FieldFulfillmentStatus, lotterydraw.FieldFulfillmentError, lotterydraw.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case lotterydraw.FieldFulfilledAt, lotterydraw.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryDraw fields.
func (_m *LotteryDraw) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterydraw.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotterydraw.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case lotterydraw.FieldActivityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field activity_id", values[i])
			} else if value.Valid {
				_m.ActivityID = value.Int64
			}
		case lotterydraw.FieldPrizeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_id", values[i])
			} else if value.Valid {
				_m.PrizeID = new(int64)
				*_m.PrizeID = value.Int64
			}
		case lotterydraw.FieldPrizeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_name", values[i])
			} else if value.Valid {
				_m.PrizeName = value.String
			}
		case lotterydraw.FieldPrizeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_type", values[i])
			} else if value.Valid {
				_m.PrizeType = value.String
			}
		case lotterydraw.FieldPrizeValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_value", values[i])
			} else if value.Valid {
				_m.PrizeValue = value.Float64
			}
		case lotterydraw.FieldRulesVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rules_version", values[i])
			} else if value.Valid {
				_m.RulesVersion = int(value.Int64)
			}
		case lotterydraw.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case lotterydraw.FieldBalanceSpentAtDraw:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_spent_at_draw", values[i])
			} else if value.Valid {
				_m.BalanceSpentAtDraw = value.Float64
			}
		case lotterydraw.FieldFulfillmentStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fulfillment_status", values[i])
			} else if value.Valid {
				_m.FulfillmentStatus = value.String
			}
		case lotterydraw.FieldFulfilledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fulfilled_at", values[i])
			} else if value.Valid {
				_m.FulfilledAt = new(time.Time)
				*_m.FulfilledAt = value.Time
			}
		case lotterydraw.FieldFulfillmentError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fulfillment_error", values[i])
			} else if value.Valid {
				_m.FulfillmentError = new(string)
				*_m.FulfillmentError = value.String
			}
		case lotterydraw.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case lotterydraw.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryDraw.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryDraw) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryDraw.
// Note that you need to call LotteryDraw.Unwrap() before calling this method if this LotteryDraw
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryDraw) Update() *LotteryDrawUpdateOne {
	return NewLotteryDrawClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryDraw entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryDraw) Unwrap() *LotteryDraw {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryDraw is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryDraw) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryDraw(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("activity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActivityID))
	builder.WriteString(", ")
	if v := _m.PrizeID; v != nil {
		builder.WriteString("prize_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("prize_name=")
	builder.WriteString(_m.PrizeName)
	builder.WriteString(", ")
	builder.WriteString("prize_type=")
	builder.WriteString(_m.PrizeType)
	builder.WriteString(", ")
	builder.WriteString("prize_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizeValue))
	builder.WriteString(", ")
	builder.WriteString("rules_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.RulesVersion))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("balance_spent_at_draw=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceSpentAtDraw))
	builder.WriteString(", ")
	builder.WriteString("fulfillment_status=")
	builder.WriteString(_m.FulfillmentStatus)
	builder.WriteString(", ")
	if v := _m.FulfilledAt; v != nil {
		builder.WriteString("fulfilled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FulfillmentError; v != nil {
		builder.WriteString("fulfillment_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryDraws is a parsable slice of LotteryDraw.
type LotteryDraws []*LotteryDraw
