// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryPrizeUpdate is the builder for updating LotteryPrize entities.
type LotteryPrizeUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryPrizeMutation
}

// Where appends a list predicates to the LotteryPrizeUpdate builder.
func (_u *LotteryPrizeUpdate) Where(ps ...predicate.LotteryPrize) *LotteryPrizeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryPrizeUpdate) SetActivityID(v int64) *LotteryPrizeUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableActivityID(v *int64) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LotteryPrizeUpdate) SetName(v string) *LotteryPrizeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableName(v *string) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrizeType sets the "prize_type" field.
func (_u *LotteryPrizeUpdate) SetPrizeType(v string) *LotteryPrizeUpdate {
	_u.mutation.SetPrizeType(v)
	return _u
}

// SetNillablePrizeType sets the "prize_type" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillablePrizeType(v *string) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetPrizeType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *LotteryPrizeUpdate) SetValue(v float64) *LotteryPrizeUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableValue(v *float64) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *LotteryPrizeUpdate) AddValue(v float64) *LotteryPrizeUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *LotteryPrizeUpdate) SetWeight(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableWeight(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *LotteryPrizeUpdate) AddWeight(v int) *LotteryPrizeUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetMinTier sets the "min_tier" field.
func (_u *LotteryPrizeUpdate) SetMinTier(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetMinTier()
	_u.mutation.SetMinTier(v)
	return _u
}

// SetNillableMinTier sets the "min_tier" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableMinTier(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetMinTier(*v)
	}
	return _u
}

// AddMinTier adds value to the "min_tier" field.
func (_u *LotteryPrizeUpdate) AddMinTier(v int) *LotteryPrizeUpdate {
	_u.mutation.AddMinTier(v)
	return _u
}

// SetTierWeights sets the "tier_weights" field.
func (_u *LotteryPrizeUpdate) SetTierWeights(v map[string]int) *LotteryPrizeUpdate {
	_u.mutation.SetTierWeights(v)
	return _u
}

// ClearTierWeights clears the value of the "tier_weights" field.
func (_u *LotteryPrizeUpdate) ClearTierWeights() *LotteryPrizeUpdate {
	_u.mutation.ClearTierWeights()
	return _u
}

// SetStock sets the "stock" field.
func (_u *LotteryPrizeUpdate) SetStock(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableStock(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *LotteryPrizeUpdate) AddStock(v int) *LotteryPrizeUpdate {
	_u.mutation.AddStock(v)
	return _u
}

// SetStockIssued sets the "stock_issued" field.
func (_u *LotteryPrizeUpdate) SetStockIssued(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetStockIssued()
	_u.mutation.SetStockIssued(v)
	return _u
}

// SetNillableStockIssued sets the "stock_issued" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableStockIssued(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetStockIssued(*v)
	}
	return _u
}

// AddStockIssued adds value to the "stock_issued" field.
func (_u *LotteryPrizeUpdate) AddStockIssued(v int) *LotteryPrizeUpdate {
	_u.mutation.AddStockIssued(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LotteryPrizeUpdate) SetEnabled(v bool) *LotteryPrizeUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableEnabled(v *bool) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LotteryPrizeUpdate) SetSortOrder(v int) *LotteryPrizeUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LotteryPrizeUpdate) SetNillableSortOrder(v *int) *LotteryPrizeUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LotteryPrizeUpdate) AddSortOrder(v int) *LotteryPrizeUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryPrizeUpdate) SetUpdatedAt(v time.Time) *LotteryPrizeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_u *LotteryPrizeUpdate) SetActivity(v *LotteryActivity) *LotteryPrizeUpdate {
	return _u.SetActivityID(v.ID)
}

// Mutation returns the LotteryPrizeMutation object of the builder.
func (_u *LotteryPrizeUpdate) Mutation() *LotteryPrizeMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the LotteryActivity entity.
func (_u *LotteryPrizeUpdate) ClearActivity() *LotteryPrizeUpdate {
	_u.mutation.ClearActivity()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryPrizeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryPrizeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryPrizeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryPrizeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryPrizeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryprize.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryPrizeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotteryprize.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeType(); ok {
		if err := lotteryprize.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.prize_type": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryPrize.activity"`)
	}
	return nil
}

func (_u *LotteryPrizeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryprize.Table, lotteryprize.Columns, sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotteryprize.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeType(); ok {
		_spec.SetField(lotteryprize.FieldPrizeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(lotteryprize.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(lotteryprize.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinTier(); ok {
		_spec.SetField(lotteryprize.FieldMinTier, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinTier(); ok {
		_spec.AddField(lotteryprize.FieldMinTier, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TierWeights(); ok {
		_spec.SetField(lotteryprize.FieldTierWeights, field.TypeJSON, value)
	}
	if _u.mutation.TierWeightsCleared() {
		_spec.ClearField(lotteryprize.FieldTierWeights, field.TypeJSON)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(lotteryprize.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(lotteryprize.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StockIssued(); ok {
		_spec.SetField(lotteryprize.FieldStockIssued, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStockIssued(); ok {
		_spec.AddField(lotteryprize.FieldStockIssued, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(lotteryprize.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryprize.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.ActivityTable,
			Columns: []string{lotteryprize.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.ActivityTable,
			Columns: []string{lotteryprize.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryprize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryPrizeUpdateOne is the builder for updating a single LotteryPrize entity.
type LotteryPrizeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryPrizeMutation
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryPrizeUpdateOne) SetActivityID(v int64) *LotteryPrizeUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableActivityID(v *int64) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LotteryPrizeUpdateOne) SetName(v string) *LotteryPrizeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableName(v *string) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrizeType sets the "prize_type" field.
func (_u *LotteryPrizeUpdateOne) SetPrizeType(v string) *LotteryPrizeUpdateOne {
	_u.mutation.SetPrizeType(v)
	return _u
}

// SetNillablePrizeType sets the "prize_type" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillablePrizeType(v *string) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetPrizeType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *LotteryPrizeUpdateOne) SetValue(v float64) *LotteryPrizeUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableValue(v *float64) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *LotteryPrizeUpdateOne) AddValue(v float64) *LotteryPrizeUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *LotteryPrizeUpdateOne) SetWeight(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableWeight(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *LotteryPrizeUpdateOne) AddWeight(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetMinTier sets the "min_tier" field.
func (_u *LotteryPrizeUpdateOne) SetMinTier(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetMinTier()
	_u.mutation.SetMinTier(v)
	return _u
}

// SetNillableMinTier sets the "min_tier" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableMinTier(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetMinTier(*v)
	}
	return _u
}

// AddMinTier adds value to the "min_tier" field.
func (_u *LotteryPrizeUpdateOne) AddMinTier(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddMinTier(v)
	return _u
}

// SetTierWeights sets the "tier_weights" field.
func (_u *LotteryPrizeUpdateOne) SetTierWeights(v map[string]int) *LotteryPrizeUpdateOne {
	_u.mutation.SetTierWeights(v)
	return _u
}

// ClearTierWeights clears the value of the "tier_weights" field.
func (_u *LotteryPrizeUpdateOne) ClearTierWeights() *LotteryPrizeUpdateOne {
	_u.mutation.ClearTierWeights()
	return _u
}

// SetStock sets the "stock" field.
func (_u *LotteryPrizeUpdateOne) SetStock(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableStock(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *LotteryPrizeUpdateOne) AddStock(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddStock(v)
	return _u
}

// SetStockIssued sets the "stock_issued" field.
func (_u *LotteryPrizeUpdateOne) SetStockIssued(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetStockIssued()
	_u.mutation.SetStockIssued(v)
	return _u
}

// SetNillableStockIssued sets the "stock_issued" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableStockIssued(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetStockIssued(*v)
	}
	return _u
}

// AddStockIssued adds value to the "stock_issued" field.
func (_u *LotteryPrizeUpdateOne) AddStockIssued(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddStockIssued(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LotteryPrizeUpdateOne) SetEnabled(v bool) *LotteryPrizeUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableEnabled(v *bool) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LotteryPrizeUpdateOne) SetSortOrder(v int) *LotteryPrizeUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LotteryPrizeUpdateOne) SetNillableSortOrder(v *int) *LotteryPrizeUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LotteryPrizeUpdateOne) AddSortOrder(v int) *LotteryPrizeUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryPrizeUpdateOne) SetUpdatedAt(v time.Time) *LotteryPrizeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_u *LotteryPrizeUpdateOne) SetActivity(v *LotteryActivity) *LotteryPrizeUpdateOne {
	return _u.SetActivityID(v.ID)
}

// Mutation returns the LotteryPrizeMutation object of the builder.
func (_u *LotteryPrizeUpdateOne) Mutation() *LotteryPrizeMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the LotteryActivity entity.
func (_u *LotteryPrizeUpdateOne) ClearActivity() *LotteryPrizeUpdateOne {
	_u.mutation.ClearActivity()
	return _u
}

// Where appends a list predicates to the LotteryPrizeUpdate builder.
func (_u *LotteryPrizeUpdateOne) Where(ps ...predicate.LotteryPrize) *LotteryPrizeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryPrizeUpdateOne) Select(field string, fields ...string) *LotteryPrizeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryPrize entity.
func (_u *LotteryPrizeUpdateOne) Save(ctx context.Context) (*LotteryPrize, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryPrizeUpdateOne) SaveX(ctx context.Context) *LotteryPrize {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryPrizeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryPrizeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryPrizeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryprize.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryPrizeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotteryprize.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeType(); ok {
		if err := lotteryprize.PrizeTypeValidator(v); err != nil {
			return &ValidationError{Name: "prize_type", err: fmt.Errorf(`ent: validator failed for field "LotteryPrize.prize_type": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryPrize.activity"`)
	}
	return nil
}

func (_u *LotteryPrizeUpdateOne) sqlSave(ctx context.Context) (_node *LotteryPrize, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryprize.Table, lotteryprize.Columns, sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryPrize.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryprize.FieldID)
		for _, f := range fields {
			if !lotteryprize.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryprize.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotteryprize.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeType(); ok {
		_spec.SetField(lotteryprize.FieldPrizeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(lotteryprize.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(lotteryprize.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(lotteryprize.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinTier(); ok {
		_spec.SetField(lotteryprize.FieldMinTier, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinTier(); ok {
		_spec.AddField(lotteryprize.FieldMinTier, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TierWeights(); ok {
		_spec.SetField(lotteryprize.FieldTierWeights, field.TypeJSON, value)
	}
	if _u.mutation.TierWeightsCleared() {
		_spec.ClearField(lotteryprize.FieldTierWeights, field.TypeJSON)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(lotteryprize.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(lotteryprize.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StockIssued(); ok {
		_spec.SetField(lotteryprize.FieldStockIssued, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStockIssued(); ok {
		_spec.AddField(lotteryprize.FieldStockIssued, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(lotteryprize.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(lotteryprize.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryprize.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.ActivityTable,
			Columns: []string{lotteryprize.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryprize.ActivityTable,
			Columns: []string{lotteryprize.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryPrize{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryprize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
