// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
)

// LotteryActivity is the model entity for the LotteryActivity schema.
type LotteryActivity struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 活动名称
	Name string `json:"name,omitempty"`
	// 状态: draft, active, paused, ended
	Status string `json:"status,omitempty"`
	// 抽奖规则版本号，随规则修改递增
	RulesVersion int `json:"rules_version,omitempty"`
	// 活动开始时间，null 表示立即开始
	StartsAt *time.Time `json:"starts_at,omitempty"`
	// 活动结束时间，null 表示不自动结束
	EndsAt *time.Time `json:"ends_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LotteryActivityQuery when eager-loading is set.
	Edges        LotteryActivityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LotteryActivityEdges holds the relations/edges for other nodes in the graph.
type LotteryActivityEdges struct {
	// Prizes holds the value of the prizes edge.
	Prizes []*LotteryPrize `json:"prizes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PrizesOrErr returns the Prizes value or an error if the edge
// was not loaded in eager-loading.
func (e LotteryActivityEdges) PrizesOrErr() ([]*LotteryPrize, error) {
	if e.loadedTypes[0] {
		return e.Prizes, nil
	}
	return nil, &NotLoadedError{edge: "prizes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryActivity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotteryactivity.FieldID, lotteryactivity.FieldRulesVersion:
			values[i] = new(sql.NullInt64)
		case lotteryactivity.FieldName, lotteryactivity.FieldStatus:
			values[i] = new(sql.NullString)
		case lotteryactivity.FieldStartsAt, lotteryactivity.FieldEndsAt, lotteryactivity.FieldCreatedAt, lotteryactivity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryActivity fields.
func (_m *LotteryActivity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotteryactivity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotteryactivity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case lotteryactivity.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case lotteryactivity.FieldRulesVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rules_version", values[i])
			} else if value.Valid {
				_m.RulesVersion = int(value.Int64)
			}
		case lotteryactivity.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = new(time.Time)
				*_m.StartsAt = value.Time
			}
		case lotteryactivity.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = new(time.Time)
				*_m.EndsAt = value.Time
			}
		case lotteryactivity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case lotteryactivity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryActivity.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryActivity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrizes queries the "prizes" edge of the LotteryActivity entity.
func (_m *LotteryActivity) QueryPrizes() *LotteryPrizeQuery {
	return NewLotteryActivityClient(_m.config).QueryPrizes(_m)
}

// Update returns a builder for updating this LotteryActivity.
// Note that you need to call LotteryActivity.Unwrap() before calling this method if this LotteryActivity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryActivity) Update() *LotteryActivityUpdateOne {
	return NewLotteryActivityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryActivity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryActivity) Unwrap() *LotteryActivity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryActivity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryActivity) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryActivity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("rules_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.RulesVersion))
	builder.WriteString(", ")
	if v := _m.StartsAt; v != nil {
		builder.WriteString("starts_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndsAt; v != nil {
		builder.WriteString("ends_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryActivities is a parsable slice of LotteryActivity.
type LotteryActivities []*LotteryActivity
