// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
)

// LotteryPrize is the model entity for the LotteryPrize schema.
type LotteryPrize struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 所属活动 ID
	ActivityID int64 `json:"activity_id,omitempty"`
	// 奖品名称
	Name string `json:"name,omitempty"`
	// 奖品类型: none, balance_bonus, quota
	PrizeType string `json:"prize_type,omitempty"`
	// 奖品数值: balance_bonus 为金额，quota 为额度，none 为 0
	Value float64 `json:"value,omitempty"`
	// 中奖权重(基础)，0 表示不参与随机；tier_weights 未覆盖的 tier 使用该值
	Weight int `json:"weight,omitempty"`
	// 可中该奖品的最低用户阶梯(0 青铜/1 白银/2 黄金/3 钻石/4 王者)，低于该阶梯的奖品不参与随机
	MinTier int `json:"min_tier,omitempty"`
	// 按阶梯覆盖权重: key 为 tier 数字字符串，如 {"0":70,"1":50}；缺失的 tier 回退 weight，显式 0 表示该 tier 不可中
	TierWeights map[string]int `json:"tier_weights,omitempty"`
	// 库存，-1 表示无限
	Stock int `json:"stock,omitempty"`
	// 已发放数量
	StockIssued int `json:"stock_issued,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 展示排序
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LotteryPrizeQuery when eager-loading is set.
	Edges        LotteryPrizeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LotteryPrizeEdges holds the relations/edges for other nodes in the graph.
type LotteryPrizeEdges struct {
	// Activity holds the value of the activity edge.
	Activity *LotteryActivity `json:"activity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ActivityOrErr returns the Activity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LotteryPrizeEdges) ActivityOrErr() (*LotteryActivity, error) {
	if e.Activity != nil {
		return e.Activity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: lotteryactivity.Label}
	}
	return nil, &NotLoadedError{edge: "activity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryPrize) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotteryprize.FieldTierWeights:
			values[i] = new([]byte)
		case lotteryprize.FieldEnabled:
			values[i] = new(sql.NullBool)
		case lotteryprize.FieldValue:
			values[i] = new(sql.NullFloat64)
		case lotteryprize.FieldID, lotteryprize.FieldActivityID, lotteryprize.FieldWeight, lotteryprize.FieldMinTier, lotteryprize.FieldStock, lotteryprize.FieldStockIssued, lotteryprize.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case lotteryprize.FieldName, lotteryprize.FieldPrizeType:
			values[i] = new(sql.NullString)
		case lotteryprize.FieldCreatedAt, lotteryprize.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryPrize fields.
func (_m *LotteryPrize) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotteryprize.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotteryprize.FieldActivityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field activity_id", values[i])
			} else if value.Valid {
				_m.ActivityID = value.Int64
			}
		case lotteryprize.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case lotteryprize.FieldPrizeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_type", values[i])
			} else if value.Valid {
				_m.PrizeType = value.String
			}
		case lotteryprize.FieldValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.Float64
			}
		case lotteryprize.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case lotteryprize.FieldMinTier:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_tier", values[i])
			} else if value.Valid {
				_m.MinTier = int(value.Int64)
			}
		case lotteryprize.FieldTierWeights:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tier_weights", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TierWeights); err != nil {
					return fmt.Errorf("unmarshal field tier_weights: %w", err)
				}
			}
		case lotteryprize.FieldStock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stock", values[i])
			} else if value.Valid {
				_m.Stock = int(value.Int64)
			}
		case lotteryprize.FieldStockIssued:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stock_issued", values[i])
			} else if value.Valid {
				_m.StockIssued = int(value.Int64)
			}
		case lotteryprize.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case lotteryprize.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case lotteryprize.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case lotteryprize.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the LotteryPrize.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryPrize) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActivity queries the "activity" edge of the LotteryPrize entity.
func (_m *LotteryPrize) QueryActivity() *LotteryActivityQuery {
	return NewLotteryPrizeClient(_m.config).QueryActivity(_m)
}

// Update returns a builder for updating this LotteryPrize.
// Note that you need to call LotteryPrize.Unwrap() before calling this method if this LotteryPrize
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryPrize) Update() *LotteryPrizeUpdateOne {
	return NewLotteryPrizeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryPrize entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryPrize) Unwrap() *LotteryPrize {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryPrize is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryPrize) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryPrize(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("activity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActivityID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("prize_type=")
	builder.WriteString(_m.PrizeType)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("min_tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinTier))
	builder.WriteString(", ")
	builder.WriteString("tier_weights=")
	builder.WriteString(fmt.Sprintf("%v", _m.TierWeights))
	builder.WriteString(", ")
	builder.WriteString("stock=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stock))
	builder.WriteString(", ")
	builder.WriteString("stock_issued=")
	builder.WriteString(fmt.Sprintf("%v", _m.StockIssued))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryPrizes is a parsable slice of LotteryPrize.
type LotteryPrizes []*LotteryPrize
