// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryuserstats"
)

// LotteryUserStatsCreate is the builder for creating a LotteryUserStats entity.
type LotteryUserStatsCreate struct {
	config
	mutation *LotteryUserStatsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *LotteryUserStatsCreate) SetUserID(v int64) *LotteryUserStatsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFirstDrawGranted sets the "first_draw_granted" field.
func (_c *LotteryUserStatsCreate) SetFirstDrawGranted(v bool) *LotteryUserStatsCreate {
	_c.mutation.SetFirstDrawGranted(v)
	return _c
}

// SetNillableFirstDrawGranted sets the "first_draw_granted" field if the given value is not nil.
func (_c *LotteryUserStatsCreate) SetNillableFirstDrawGranted(v *bool) *LotteryUserStatsCreate {
	if v != nil {
		_c.SetFirstDrawGranted(*v)
	}
	return _c
}

// SetBaselineAt sets the "baseline_at" field.
func (_c *LotteryUserStatsCreate) SetBaselineAt(v time.Time) *LotteryUserStatsCreate {
	_c.mutation.SetBaselineAt(v)
	return _c
}

// SetManualAdjustment sets the "manual_adjustment" field.
func (_c *LotteryUserStatsCreate) SetManualAdjustment(v int) *LotteryUserStatsCreate {
	_c.mutation.SetManualAdjustment(v)
	return _c
}

// SetNillableManualAdjustment sets the "manual_adjustment" field if the given value is not nil.
func (_c *LotteryUserStatsCreate) SetNillableManualAdjustment(v *int) *LotteryUserStatsCreate {
	if v != nil {
		_c.SetManualAdjustment(*v)
	}
	return _c
}

// SetSpendOffsetCents sets the "spend_offset_cents" field.
func (_c *LotteryUserStatsCreate) SetSpendOffsetCents(v int64) *LotteryUserStatsCreate {
	_c.mutation.SetSpendOffsetCents(v)
	return _c
}

// SetNillableSpendOffsetCents sets the "spend_offset_cents" field if the given value is not nil.
func (_c *LotteryUserStatsCreate) SetNillableSpendOffsetCents(v *int64) *LotteryUserStatsCreate {
	if v != nil {
		_c.SetSpendOffsetCents(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryUserStatsCreate) SetCreatedAt(v time.Time) *LotteryUserStatsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryUserStatsCreate) SetNillableCreatedAt(v *time.Time) *LotteryUserStatsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryUserStatsCreate) SetUpdatedAt(v time.Time) *LotteryUserStatsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryUserStatsCreate) SetNillableUpdatedAt(v *time.Time) *LotteryUserStatsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the LotteryUserStatsMutation object of the builder.
func (_c *LotteryUserStatsCreate) Mutation() *LotteryUserStatsMutation {
	return _c.mutation
}

// Save creates the LotteryUserStats in the database.
func (_c *LotteryUserStatsCreate) Save(ctx context.Context) (*LotteryUserStats, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryUserStatsCreate) SaveX(ctx context.Context) *LotteryUserStats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryUserStatsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryUserStatsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryUserStatsCreate) defaults() {
	if _, ok := _c.mutation.FirstDrawGranted(); !ok {
		v := lotteryuserstats.DefaultFirstDrawGranted
		_c.mutation.SetFirstDrawGranted(v)
	}
	if _, ok := _c.mutation.ManualAdjustment(); !ok {
		v := lotteryuserstats.DefaultManualAdjustment
		_c.mutation.SetManualAdjustment(v)
	}
	if _, ok := _c.mutation.SpendOffsetCents(); !ok {
		v := lotteryuserstats.DefaultSpendOffsetCents
		_c.mutation.SetSpendOffsetCents(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotteryuserstats.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotteryuserstats.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryUserStatsCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryUserStats.user_id"`)}
	}
	if _, ok := _c.mutation.FirstDrawGranted(); !ok {
		return &ValidationError{Name: "first_draw_granted", err: errors.New(`ent: missing required field "LotteryUserStats.first_draw_granted"`)}
	}
	if _, ok := _c.mutation.BaselineAt(); !ok {
		return &ValidationError{Name: "baseline_at", err: errors.New(`ent: missing required field "LotteryUserStats.baseline_at"`)}
	}
	if _, ok := _c.mutation.ManualAdjustment(); !ok {
		return &ValidationError{Name: "manual_adjustment", err: errors.New(`ent: missing required field "LotteryUserStats.manual_adjustment"`)}
	}
	if _, ok := _c.mutation.SpendOffsetCents(); !ok {
		return &ValidationError{Name: "spend_offset_cents", err: errors.New(`ent: missing required field "LotteryUserStats.spend_offset_cents"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryUserStats.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryUserStats.updated_at"`)}
	}
	return nil
}

func (_c *LotteryUserStatsCreate) sqlSave(ctx context.Context) (*LotteryUserStats, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryUserStatsCreate) createSpec() (*LotteryUserStats, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryUserStats{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryuserstats.Table, sqlgraph.NewFieldSpec(lotteryuserstats.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotteryuserstats.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.FirstDrawGranted(); ok {
		_spec.SetField(lotteryuserstats.FieldFirstDrawGranted, field.TypeBool, value)
		_node.FirstDrawGranted = value
	}
	if value, ok := _c.mutation.BaselineAt(); ok {
		_spec.SetField(lotteryuserstats.FieldBaselineAt, field.TypeTime, value)
		_node.BaselineAt = value
	}
	if value, ok := _c.mutation.ManualAdjustment(); ok {
		_spec.SetField(lotteryuserstats.FieldManualAdjustment, field.TypeInt, value)
		_node.ManualAdjustment = value
	}
	if value, ok := _c.mutation.SpendOffsetCents(); ok {
		_spec.SetField(lotteryuserstats.FieldSpendOffsetCents, field.TypeInt64, value)
		_node.SpendOffsetCents = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryuserstats.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryuserstats.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryUserStats.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryUserStatsUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryUserStatsCreate) OnConflict(opts ...sql.ConflictOption) *LotteryUserStatsUpsertOne {
	_c.conflict = opts
	return &LotteryUserStatsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryUserStats.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryUserStatsCreate) OnConflictColumns(columns ...string) *LotteryUserStatsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryUserStatsUpsertOne{
		create: _c,
	}
}

type (
	// LotteryUserStatsUpsertOne is the builder for "upsert"-ing
	//  one LotteryUserStats node.
	LotteryUserStatsUpsertOne struct {
		create *LotteryUserStatsCreate
	}

	// LotteryUserStatsUpsert is the "OnConflict" setter.
	LotteryUserStatsUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *LotteryUserStatsUpsert) SetUserID(v int64) *LotteryUserStatsUpsert {
	u.Set(lotteryuserstats.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryUserStatsUpsert) UpdateUserID() *LotteryUserStatsUpsert {
	u.SetExcluded(lotteryuserstats.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryUserStatsUpsert) AddUserID(v int64) *LotteryUserStatsUpsert {
	u.Add(lotteryuserstats.FieldUserID, v)
	return u
}

// SetFirstDrawGranted sets the "first_draw_granted" field.
func (u *LotteryUserStatsUpsert) SetFirstDrawGranted(v bool) *LotteryUserStatsUpsert {
	u.Set(lotteryuserstats.FieldFirstDrawGranted, v)
	return u
}

// UpdateFirstDrawGranted sets the "first_draw_granted" field to the value that was provided on create.
func (u *LotteryUserStatsUpsert) UpdateFirstDrawGranted() *LotteryUserStatsUpsert {
	u.SetExcluded(lotteryuserstats.FieldFirstDrawGranted)
	return u
}

// SetBaselineAt sets the "baseline_at" field.
func (u *LotteryUserStatsUpsert) SetBaselineAt(v time.Time) *LotteryUserStatsUpsert {
	u.Set(lotteryuserstats.FieldBaselineAt, v)
	return u
}

// UpdateBaselineAt sets the "baseline_at" field to the value that was provided on create.
func (u *LotteryUserStatsUpsert) UpdateBaselineAt() *LotteryUserStatsUpsert {
	u.SetExcluded(lotteryuserstats.FieldBaselineAt)
	return u
}

// SetManualAdjustment sets the "manual_adjustment" field.
func (u *LotteryUserStatsUpsert) SetManualAdjustment(v int) *LotteryUserStatsUpsert {
	u.Set(lotteryuserstats.FieldManualAdjustment, v)
	return u
}

// UpdateManualAdjustment sets the "manual_adjustment" field to the value that was provided on create.
func (u *LotteryUserStatsUpsert) UpdateManualAdjustment() *LotteryUserStatsUpsert {
	u.SetExcluded(lotteryuserstats.FieldManualAdjustment)
	return u
}

// AddManualAdjustment adds v to the "manual_adjustment" field.
func (u *LotteryUserStatsUpsert) AddManualAdjustment(v int) *LotteryUserStatsUpsert {
	u.Add(lotteryuserstats.FieldManualAdjustment, v)
	return u
}

// SetSpendOffsetCents sets the "spend_offset_cents" field.
func (u *LotteryUserStatsUpsert) SetSpendOffsetCents(v int64) *LotteryUserStatsUpsert {
	u.Set(lotteryuserstats.FieldSpendOffsetCents, v)
	return u
}

// UpdateSpendOffsetCents sets the "spend_offset_cents" field to the value that was provided on create.
func (u *LotteryUserStatsUpsert) UpdateSpendOffsetCents() *LotteryUserStatsUpsert {
	u.SetExcluded(lotteryuserstats.FieldSpendOffsetCents)
	return u
}

// AddSpendOffsetCents adds v to the "spend_offset_cents" field.
func (u *LotteryUserStatsUpsert) AddSpendOffsetCents(v int64) *LotteryUserStatsUpsert {
	u.Add(lotteryuserstats.FieldSpendOffsetCents, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryUserStatsUpsert) SetUpdatedAt(v time.Time) *LotteryUserStatsUpsert {
	u.Set(lotteryuserstats.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryUserStatsUpsert) UpdateUpdatedAt() *LotteryUserStatsUpsert {
	u.SetExcluded(lotteryuserstats.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryUserStats.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryUserStatsUpsertOne) UpdateNewValues() *LotteryUserStatsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotteryuserstats.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryUserStats.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryUserStatsUpsertOne) Ignore() *LotteryUserStatsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryUserStatsUpsertOne) DoNothing() *LotteryUserStatsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryUserStatsCreate.OnConflict
// documentation for more info.
func (u *LotteryUserStatsUpsertOne) Update(set func(*LotteryUserStatsUpsert)) *LotteryUserStatsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryUserStatsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryUserStatsUpsertOne) SetUserID(v int64) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryUserStatsUpsertOne) AddUserID(v int64) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertOne) UpdateUserID() *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateUserID()
	})
}

// SetFirstDrawGranted sets the "first_draw_granted" field.
func (u *LotteryUserStatsUpsertOne) SetFirstDrawGranted(v bool) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetFirstDrawGranted(v)
	})
}

// UpdateFirstDrawGranted sets the "first_draw_granted" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertOne) UpdateFirstDrawGranted() *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateFirstDrawGranted()
	})
}

// SetBaselineAt sets the "baseline_at" field.
func (u *LotteryUserStatsUpsertOne) SetBaselineAt(v time.Time) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetBaselineAt(v)
	})
}

// UpdateBaselineAt sets the "baseline_at" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertOne) UpdateBaselineAt() *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateBaselineAt()
	})
}

// SetManualAdjustment sets the "manual_adjustment" field.
func (u *LotteryUserStatsUpsertOne) SetManualAdjustment(v int) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetManualAdjustment(v)
	})
}

// AddManualAdjustment adds v to the "manual_adjustment" field.
func (u *LotteryUserStatsUpsertOne) AddManualAdjustment(v int) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.AddManualAdjustment(v)
	})
}

// UpdateManualAdjustment sets the "manual_adjustment" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertOne) UpdateManualAdjustment() *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateManualAdjustment()
	})
}

// SetSpendOffsetCents sets the "spend_offset_cents" field.
func (u *LotteryUserStatsUpsertOne) SetSpendOffsetCents(v int64) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetSpendOffsetCents(v)
	})
}

// AddSpendOffsetCents adds v to the "spend_offset_cents" field.
func (u *LotteryUserStatsUpsertOne) AddSpendOffsetCents(v int64) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.AddSpendOffsetCents(v)
	})
}

// UpdateSpendOffsetCents sets the "spend_offset_cents" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertOne) UpdateSpendOffsetCents() *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateSpendOffsetCents()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryUserStatsUpsertOne) SetUpdatedAt(v time.Time) *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertOne) UpdateUpdatedAt() *LotteryUserStatsUpsertOne {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryUserStatsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryUserStatsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryUserStatsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryUserStatsUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryUserStatsUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryUserStatsCreateBulk is the builder for creating many LotteryUserStats entities in bulk.
type LotteryUserStatsCreateBulk struct {
	config
	err      error
	builders []*LotteryUserStatsCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryUserStats entities in the database.
func (_c *LotteryUserStatsCreateBulk) Save(ctx context.Context) ([]*LotteryUserStats, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryUserStats, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryUserStatsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryUserStatsCreateBulk) SaveX(ctx context.Context) []*LotteryUserStats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryUserStatsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryUserStatsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryUserStats.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryUserStatsUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryUserStatsCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryUserStatsUpsertBulk {
	_c.conflict = opts
	return &LotteryUserStatsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryUserStats.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryUserStatsCreateBulk) OnConflictColumns(columns ...string) *LotteryUserStatsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryUserStatsUpsertBulk{
		create: _c,
	}
}

// LotteryUserStatsUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryUserStats nodes.
type LotteryUserStatsUpsertBulk struct {
	create *LotteryUserStatsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryUserStats.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryUserStatsUpsertBulk) UpdateNewValues() *LotteryUserStatsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotteryuserstats.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryUserStats.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryUserStatsUpsertBulk) Ignore() *LotteryUserStatsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryUserStatsUpsertBulk) DoNothing() *LotteryUserStatsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryUserStatsCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryUserStatsUpsertBulk) Update(set func(*LotteryUserStatsUpsert)) *LotteryUserStatsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryUserStatsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryUserStatsUpsertBulk) SetUserID(v int64) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryUserStatsUpsertBulk) AddUserID(v int64) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertBulk) UpdateUserID() *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateUserID()
	})
}

// SetFirstDrawGranted sets the "first_draw_granted" field.
func (u *LotteryUserStatsUpsertBulk) SetFirstDrawGranted(v bool) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetFirstDrawGranted(v)
	})
}

// UpdateFirstDrawGranted sets the "first_draw_granted" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertBulk) UpdateFirstDrawGranted() *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateFirstDrawGranted()
	})
}

// SetBaselineAt sets the "baseline_at" field.
func (u *LotteryUserStatsUpsertBulk) SetBaselineAt(v time.Time) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetBaselineAt(v)
	})
}

// UpdateBaselineAt sets the "baseline_at" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertBulk) UpdateBaselineAt() *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateBaselineAt()
	})
}

// SetManualAdjustment sets the "manual_adjustment" field.
func (u *LotteryUserStatsUpsertBulk) SetManualAdjustment(v int) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetManualAdjustment(v)
	})
}

// AddManualAdjustment adds v to the "manual_adjustment" field.
func (u *LotteryUserStatsUpsertBulk) AddManualAdjustment(v int) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.AddManualAdjustment(v)
	})
}

// UpdateManualAdjustment sets the "manual_adjustment" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertBulk) UpdateManualAdjustment() *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateManualAdjustment()
	})
}

// SetSpendOffsetCents sets the "spend_offset_cents" field.
func (u *LotteryUserStatsUpsertBulk) SetSpendOffsetCents(v int64) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetSpendOffsetCents(v)
	})
}

// AddSpendOffsetCents adds v to the "spend_offset_cents" field.
func (u *LotteryUserStatsUpsertBulk) AddSpendOffsetCents(v int64) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.AddSpendOffsetCents(v)
	})
}

// UpdateSpendOffsetCents sets the "spend_offset_cents" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertBulk) UpdateSpendOffsetCents() *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateSpendOffsetCents()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryUserStatsUpsertBulk) SetUpdatedAt(v time.Time) *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryUserStatsUpsertBulk) UpdateUpdatedAt() *LotteryUserStatsUpsertBulk {
	return u.Update(func(s *LotteryUserStatsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryUserStatsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryUserStatsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryUserStatsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryUserStatsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
