// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprize"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryActivityUpdate is the builder for updating LotteryActivity entities.
type LotteryActivityUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryActivityMutation
}

// Where appends a list predicates to the LotteryActivityUpdate builder.
func (_u *LotteryActivityUpdate) Where(ps ...predicate.LotteryActivity) *LotteryActivityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *LotteryActivityUpdate) SetName(v string) *LotteryActivityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryActivityUpdate) SetNillableName(v *string) *LotteryActivityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryActivityUpdate) SetStatus(v string) *LotteryActivityUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryActivityUpdate) SetNillableStatus(v *string) *LotteryActivityUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRulesVersion sets the "rules_version" field.
func (_u *LotteryActivityUpdate) SetRulesVersion(v int) *LotteryActivityUpdate {
	_u.mutation.ResetRulesVersion()
	_u.mutation.SetRulesVersion(v)
	return _u
}

// SetNillableRulesVersion sets the "rules_version" field if the given value is not nil.
func (_u *LotteryActivityUpdate) SetNillableRulesVersion(v *int) *LotteryActivityUpdate {
	if v != nil {
		_u.SetRulesVersion(*v)
	}
	return _u
}

// AddRulesVersion adds value to the "rules_version" field.
func (_u *LotteryActivityUpdate) AddRulesVersion(v int) *LotteryActivityUpdate {
	_u.mutation.AddRulesVersion(v)
	return _u
}

// SetTierMode sets the "tier_mode" field.
func (_u *LotteryActivityUpdate) SetTierMode(v string) *LotteryActivityUpdate {
	_u.mutation.SetTierMode(v)
	return _u
}

// SetNillableTierMode sets the "tier_mode" field if the given value is not nil.
func (_u *LotteryActivityUpdate) SetNillableTierMode(v *string) *LotteryActivityUpdate {
	if v != nil {
		_u.SetTierMode(*v)
	}
	return _u
}

// SetTierThresholds sets the "tier_thresholds" field.
func (_u *LotteryActivityUpdate) SetTierThresholds(v []int64) *LotteryActivityUpdate {
	_u.mutation.SetTierThresholds(v)
	return _u
}

// AppendTierThresholds appends value to the "tier_thresholds" field.
func (_u *LotteryActivityUpdate) AppendTierThresholds(v []int64) *LotteryActivityUpdate {
	_u.mutation.AppendTierThresholds(v)
	return _u
}

// ClearTierThresholds clears the value of the "tier_thresholds" field.
func (_u *LotteryActivityUpdate) ClearTierThresholds() *LotteryActivityUpdate {
	_u.mutation.ClearTierThresholds()
	return _u
}

// SetTierDefinitions sets the "tier_definitions" field.
func (_u *LotteryActivityUpdate) SetTierDefinitions(v []map[string]interface{}) *LotteryActivityUpdate {
	_u.mutation.SetTierDefinitions(v)
	return _u
}

// AppendTierDefinitions appends value to the "tier_definitions" field.
func (_u *LotteryActivityUpdate) AppendTierDefinitions(v []map[string]interface{}) *LotteryActivityUpdate {
	_u.mutation.AppendTierDefinitions(v)
	return _u
}

// ClearTierDefinitions clears the value of the "tier_definitions" field.
func (_u *LotteryActivityUpdate) ClearTierDefinitions() *LotteryActivityUpdate {
	_u.mutation.ClearTierDefinitions()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *LotteryActivityUpdate) SetStartsAt(v time.Time) *LotteryActivityUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *LotteryActivityUpdate) SetNillableStartsAt(v *time.Time) *LotteryActivityUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *LotteryActivityUpdate) ClearStartsAt() *LotteryActivityUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *LotteryActivityUpdate) SetEndsAt(v time.Time) *LotteryActivityUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *LotteryActivityUpdate) SetNillableEndsAt(v *time.Time) *LotteryActivityUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *LotteryActivityUpdate) ClearEndsAt() *LotteryActivityUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryActivityUpdate) SetUpdatedAt(v time.Time) *LotteryActivityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPrizeIDs adds the "prizes" edge to the LotteryPrize entity by IDs.
func (_u *LotteryActivityUpdate) AddPrizeIDs(ids ...int64) *LotteryActivityUpdate {
	_u.mutation.AddPrizeIDs(ids...)
	return _u
}

// AddPrizes adds the "prizes" edges to the LotteryPrize entity.
func (_u *LotteryActivityUpdate) AddPrizes(v ...*LotteryPrize) *LotteryActivityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrizeIDs(ids...)
}

// Mutation returns the LotteryActivityMutation object of the builder.
func (_u *LotteryActivityUpdate) Mutation() *LotteryActivityMutation {
	return _u.mutation
}

// ClearPrizes clears all "prizes" edges to the LotteryPrize entity.
func (_u *LotteryActivityUpdate) ClearPrizes() *LotteryActivityUpdate {
	_u.mutation.ClearPrizes()
	return _u
}

// RemovePrizeIDs removes the "prizes" edge to LotteryPrize entities by IDs.
func (_u *LotteryActivityUpdate) RemovePrizeIDs(ids ...int64) *LotteryActivityUpdate {
	_u.mutation.RemovePrizeIDs(ids...)
	return _u
}

// RemovePrizes removes "prizes" edges to LotteryPrize entities.
func (_u *LotteryActivityUpdate) RemovePrizes(v ...*LotteryPrize) *LotteryActivityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrizeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryActivityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryActivityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryActivityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryActivityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryActivityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryactivity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryActivityUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotteryactivity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := lotteryactivity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TierMode(); ok {
		if err := lotteryactivity.TierModeValidator(v); err != nil {
			return &ValidationError{Name: "tier_mode", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.tier_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryActivityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryactivity.Table, lotteryactivity.Columns, sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotteryactivity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotteryactivity.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RulesVersion(); ok {
		_spec.SetField(lotteryactivity.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRulesVersion(); ok {
		_spec.AddField(lotteryactivity.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TierMode(); ok {
		_spec.SetField(lotteryactivity.FieldTierMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TierThresholds(); ok {
		_spec.SetField(lotteryactivity.FieldTierThresholds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTierThresholds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, lotteryactivity.FieldTierThresholds, value)
		})
	}
	if _u.mutation.TierThresholdsCleared() {
		_spec.ClearField(lotteryactivity.FieldTierThresholds, field.TypeJSON)
	}
	if value, ok := _u.mutation.TierDefinitions(); ok {
		_spec.SetField(lotteryactivity.FieldTierDefinitions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTierDefinitions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, lotteryactivity.FieldTierDefinitions, value)
		})
	}
	if _u.mutation.TierDefinitionsCleared() {
		_spec.ClearField(lotteryactivity.FieldTierDefinitions, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(lotteryactivity.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(lotteryactivity.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(lotteryactivity.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(lotteryactivity.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.PrizesTable,
			Columns: []string{lotteryactivity.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrizesIDs(); len(nodes) > 0 && !_u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.PrizesTable,
			Columns: []string{lotteryactivity.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.PrizesTable,
			Columns: []string{lotteryactivity.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryActivityUpdateOne is the builder for updating a single LotteryActivity entity.
type LotteryActivityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryActivityMutation
}

// SetName sets the "name" field.
func (_u *LotteryActivityUpdateOne) SetName(v string) *LotteryActivityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryActivityUpdateOne) SetNillableName(v *string) *LotteryActivityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryActivityUpdateOne) SetStatus(v string) *LotteryActivityUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryActivityUpdateOne) SetNillableStatus(v *string) *LotteryActivityUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRulesVersion sets the "rules_version" field.
func (_u *LotteryActivityUpdateOne) SetRulesVersion(v int) *LotteryActivityUpdateOne {
	_u.mutation.ResetRulesVersion()
	_u.mutation.SetRulesVersion(v)
	return _u
}

// SetNillableRulesVersion sets the "rules_version" field if the given value is not nil.
func (_u *LotteryActivityUpdateOne) SetNillableRulesVersion(v *int) *LotteryActivityUpdateOne {
	if v != nil {
		_u.SetRulesVersion(*v)
	}
	return _u
}

// AddRulesVersion adds value to the "rules_version" field.
func (_u *LotteryActivityUpdateOne) AddRulesVersion(v int) *LotteryActivityUpdateOne {
	_u.mutation.AddRulesVersion(v)
	return _u
}

// SetTierMode sets the "tier_mode" field.
func (_u *LotteryActivityUpdateOne) SetTierMode(v string) *LotteryActivityUpdateOne {
	_u.mutation.SetTierMode(v)
	return _u
}

// SetNillableTierMode sets the "tier_mode" field if the given value is not nil.
func (_u *LotteryActivityUpdateOne) SetNillableTierMode(v *string) *LotteryActivityUpdateOne {
	if v != nil {
		_u.SetTierMode(*v)
	}
	return _u
}

// SetTierThresholds sets the "tier_thresholds" field.
func (_u *LotteryActivityUpdateOne) SetTierThresholds(v []int64) *LotteryActivityUpdateOne {
	_u.mutation.SetTierThresholds(v)
	return _u
}

// AppendTierThresholds appends value to the "tier_thresholds" field.
func (_u *LotteryActivityUpdateOne) AppendTierThresholds(v []int64) *LotteryActivityUpdateOne {
	_u.mutation.AppendTierThresholds(v)
	return _u
}

// ClearTierThresholds clears the value of the "tier_thresholds" field.
func (_u *LotteryActivityUpdateOne) ClearTierThresholds() *LotteryActivityUpdateOne {
	_u.mutation.ClearTierThresholds()
	return _u
}

// SetTierDefinitions sets the "tier_definitions" field.
func (_u *LotteryActivityUpdateOne) SetTierDefinitions(v []map[string]interface{}) *LotteryActivityUpdateOne {
	_u.mutation.SetTierDefinitions(v)
	return _u
}

// AppendTierDefinitions appends value to the "tier_definitions" field.
func (_u *LotteryActivityUpdateOne) AppendTierDefinitions(v []map[string]interface{}) *LotteryActivityUpdateOne {
	_u.mutation.AppendTierDefinitions(v)
	return _u
}

// ClearTierDefinitions clears the value of the "tier_definitions" field.
func (_u *LotteryActivityUpdateOne) ClearTierDefinitions() *LotteryActivityUpdateOne {
	_u.mutation.ClearTierDefinitions()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *LotteryActivityUpdateOne) SetStartsAt(v time.Time) *LotteryActivityUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *LotteryActivityUpdateOne) SetNillableStartsAt(v *time.Time) *LotteryActivityUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *LotteryActivityUpdateOne) ClearStartsAt() *LotteryActivityUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *LotteryActivityUpdateOne) SetEndsAt(v time.Time) *LotteryActivityUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *LotteryActivityUpdateOne) SetNillableEndsAt(v *time.Time) *LotteryActivityUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *LotteryActivityUpdateOne) ClearEndsAt() *LotteryActivityUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryActivityUpdateOne) SetUpdatedAt(v time.Time) *LotteryActivityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPrizeIDs adds the "prizes" edge to the LotteryPrize entity by IDs.
func (_u *LotteryActivityUpdateOne) AddPrizeIDs(ids ...int64) *LotteryActivityUpdateOne {
	_u.mutation.AddPrizeIDs(ids...)
	return _u
}

// AddPrizes adds the "prizes" edges to the LotteryPrize entity.
func (_u *LotteryActivityUpdateOne) AddPrizes(v ...*LotteryPrize) *LotteryActivityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrizeIDs(ids...)
}

// Mutation returns the LotteryActivityMutation object of the builder.
func (_u *LotteryActivityUpdateOne) Mutation() *LotteryActivityMutation {
	return _u.mutation
}

// ClearPrizes clears all "prizes" edges to the LotteryPrize entity.
func (_u *LotteryActivityUpdateOne) ClearPrizes() *LotteryActivityUpdateOne {
	_u.mutation.ClearPrizes()
	return _u
}

// RemovePrizeIDs removes the "prizes" edge to LotteryPrize entities by IDs.
func (_u *LotteryActivityUpdateOne) RemovePrizeIDs(ids ...int64) *LotteryActivityUpdateOne {
	_u.mutation.RemovePrizeIDs(ids...)
	return _u
}

// RemovePrizes removes "prizes" edges to LotteryPrize entities.
func (_u *LotteryActivityUpdateOne) RemovePrizes(v ...*LotteryPrize) *LotteryActivityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrizeIDs(ids...)
}

// Where appends a list predicates to the LotteryActivityUpdate builder.
func (_u *LotteryActivityUpdateOne) Where(ps ...predicate.LotteryActivity) *LotteryActivityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryActivityUpdateOne) Select(field string, fields ...string) *LotteryActivityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryActivity entity.
func (_u *LotteryActivityUpdateOne) Save(ctx context.Context) (*LotteryActivity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryActivityUpdateOne) SaveX(ctx context.Context) *LotteryActivity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryActivityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryActivityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryActivityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryactivity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryActivityUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotteryactivity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := lotteryactivity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TierMode(); ok {
		if err := lotteryactivity.TierModeValidator(v); err != nil {
			return &ValidationError{Name: "tier_mode", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.tier_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryActivityUpdateOne) sqlSave(ctx context.Context) (_node *LotteryActivity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryactivity.Table, lotteryactivity.Columns, sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryActivity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryactivity.FieldID)
		for _, f := range fields {
			if !lotteryactivity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotteryactivity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotteryactivity.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RulesVersion(); ok {
		_spec.SetField(lotteryactivity.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRulesVersion(); ok {
		_spec.AddField(lotteryactivity.FieldRulesVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TierMode(); ok {
		_spec.SetField(lotteryactivity.FieldTierMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TierThresholds(); ok {
		_spec.SetField(lotteryactivity.FieldTierThresholds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTierThresholds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, lotteryactivity.FieldTierThresholds, value)
		})
	}
	if _u.mutation.TierThresholdsCleared() {
		_spec.ClearField(lotteryactivity.FieldTierThresholds, field.TypeJSON)
	}
	if value, ok := _u.mutation.TierDefinitions(); ok {
		_spec.SetField(lotteryactivity.FieldTierDefinitions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTierDefinitions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, lotteryactivity.FieldTierDefinitions, value)
		})
	}
	if _u.mutation.TierDefinitionsCleared() {
		_spec.ClearField(lotteryactivity.FieldTierDefinitions, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(lotteryactivity.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(lotteryactivity.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(lotteryactivity.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(lotteryactivity.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.PrizesTable,
			Columns: []string{lotteryactivity.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrizesIDs(); len(nodes) > 0 && !_u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.PrizesTable,
			Columns: []string{lotteryactivity.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.PrizesTable,
			Columns: []string{lotteryactivity.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryActivity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
