// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryuserstats"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryUserStatsUpdate is the builder for updating LotteryUserStats entities.
type LotteryUserStatsUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryUserStatsMutation
}

// Where appends a list predicates to the LotteryUserStatsUpdate builder.
func (_u *LotteryUserStatsUpdate) Where(ps ...predicate.LotteryUserStats) *LotteryUserStatsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryUserStatsUpdate) SetUserID(v int64) *LotteryUserStatsUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryUserStatsUpdate) SetNillableUserID(v *int64) *LotteryUserStatsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryUserStatsUpdate) AddUserID(v int64) *LotteryUserStatsUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFirstDrawGranted sets the "first_draw_granted" field.
func (_u *LotteryUserStatsUpdate) SetFirstDrawGranted(v bool) *LotteryUserStatsUpdate {
	_u.mutation.SetFirstDrawGranted(v)
	return _u
}

// SetNillableFirstDrawGranted sets the "first_draw_granted" field if the given value is not nil.
func (_u *LotteryUserStatsUpdate) SetNillableFirstDrawGranted(v *bool) *LotteryUserStatsUpdate {
	if v != nil {
		_u.SetFirstDrawGranted(*v)
	}
	return _u
}

// SetBaselineAt sets the "baseline_at" field.
func (_u *LotteryUserStatsUpdate) SetBaselineAt(v time.Time) *LotteryUserStatsUpdate {
	_u.mutation.SetBaselineAt(v)
	return _u
}

// SetNillableBaselineAt sets the "baseline_at" field if the given value is not nil.
func (_u *LotteryUserStatsUpdate) SetNillableBaselineAt(v *time.Time) *LotteryUserStatsUpdate {
	if v != nil {
		_u.SetBaselineAt(*v)
	}
	return _u
}

// SetManualAdjustment sets the "manual_adjustment" field.
func (_u *LotteryUserStatsUpdate) SetManualAdjustment(v int) *LotteryUserStatsUpdate {
	_u.mutation.ResetManualAdjustment()
	_u.mutation.SetManualAdjustment(v)
	return _u
}

// SetNillableManualAdjustment sets the "manual_adjustment" field if the given value is not nil.
func (_u *LotteryUserStatsUpdate) SetNillableManualAdjustment(v *int) *LotteryUserStatsUpdate {
	if v != nil {
		_u.SetManualAdjustment(*v)
	}
	return _u
}

// AddManualAdjustment adds value to the "manual_adjustment" field.
func (_u *LotteryUserStatsUpdate) AddManualAdjustment(v int) *LotteryUserStatsUpdate {
	_u.mutation.AddManualAdjustment(v)
	return _u
}

// SetSpendOffsetCents sets the "spend_offset_cents" field.
func (_u *LotteryUserStatsUpdate) SetSpendOffsetCents(v int64) *LotteryUserStatsUpdate {
	_u.mutation.ResetSpendOffsetCents()
	_u.mutation.SetSpendOffsetCents(v)
	return _u
}

// SetNillableSpendOffsetCents sets the "spend_offset_cents" field if the given value is not nil.
func (_u *LotteryUserStatsUpdate) SetNillableSpendOffsetCents(v *int64) *LotteryUserStatsUpdate {
	if v != nil {
		_u.SetSpendOffsetCents(*v)
	}
	return _u
}

// AddSpendOffsetCents adds value to the "spend_offset_cents" field.
func (_u *LotteryUserStatsUpdate) AddSpendOffsetCents(v int64) *LotteryUserStatsUpdate {
	_u.mutation.AddSpendOffsetCents(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryUserStatsUpdate) SetUpdatedAt(v time.Time) *LotteryUserStatsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LotteryUserStatsMutation object of the builder.
func (_u *LotteryUserStatsUpdate) Mutation() *LotteryUserStatsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryUserStatsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryUserStatsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryUserStatsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryUserStatsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryUserStatsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryuserstats.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LotteryUserStatsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotteryuserstats.Table, lotteryuserstats.Columns, sqlgraph.NewFieldSpec(lotteryuserstats.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotteryuserstats.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotteryuserstats.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstDrawGranted(); ok {
		_spec.SetField(lotteryuserstats.FieldFirstDrawGranted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BaselineAt(); ok {
		_spec.SetField(lotteryuserstats.FieldBaselineAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ManualAdjustment(); ok {
		_spec.SetField(lotteryuserstats.FieldManualAdjustment, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedManualAdjustment(); ok {
		_spec.AddField(lotteryuserstats.FieldManualAdjustment, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SpendOffsetCents(); ok {
		_spec.SetField(lotteryuserstats.FieldSpendOffsetCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSpendOffsetCents(); ok {
		_spec.AddField(lotteryuserstats.FieldSpendOffsetCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryuserstats.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryuserstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryUserStatsUpdateOne is the builder for updating a single LotteryUserStats entity.
type LotteryUserStatsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryUserStatsMutation
}

// SetUserID sets the "user_id" field.
func (_u *LotteryUserStatsUpdateOne) SetUserID(v int64) *LotteryUserStatsUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryUserStatsUpdateOne) SetNillableUserID(v *int64) *LotteryUserStatsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryUserStatsUpdateOne) AddUserID(v int64) *LotteryUserStatsUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFirstDrawGranted sets the "first_draw_granted" field.
func (_u *LotteryUserStatsUpdateOne) SetFirstDrawGranted(v bool) *LotteryUserStatsUpdateOne {
	_u.mutation.SetFirstDrawGranted(v)
	return _u
}

// SetNillableFirstDrawGranted sets the "first_draw_granted" field if the given value is not nil.
func (_u *LotteryUserStatsUpdateOne) SetNillableFirstDrawGranted(v *bool) *LotteryUserStatsUpdateOne {
	if v != nil {
		_u.SetFirstDrawGranted(*v)
	}
	return _u
}

// SetBaselineAt sets the "baseline_at" field.
func (_u *LotteryUserStatsUpdateOne) SetBaselineAt(v time.Time) *LotteryUserStatsUpdateOne {
	_u.mutation.SetBaselineAt(v)
	return _u
}

// SetNillableBaselineAt sets the "baseline_at" field if the given value is not nil.
func (_u *LotteryUserStatsUpdateOne) SetNillableBaselineAt(v *time.Time) *LotteryUserStatsUpdateOne {
	if v != nil {
		_u.SetBaselineAt(*v)
	}
	return _u
}

// SetManualAdjustment sets the "manual_adjustment" field.
func (_u *LotteryUserStatsUpdateOne) SetManualAdjustment(v int) *LotteryUserStatsUpdateOne {
	_u.mutation.ResetManualAdjustment()
	_u.mutation.SetManualAdjustment(v)
	return _u
}

// SetNillableManualAdjustment sets the "manual_adjustment" field if the given value is not nil.
func (_u *LotteryUserStatsUpdateOne) SetNillableManualAdjustment(v *int) *LotteryUserStatsUpdateOne {
	if v != nil {
		_u.SetManualAdjustment(*v)
	}
	return _u
}

// AddManualAdjustment adds value to the "manual_adjustment" field.
func (_u *LotteryUserStatsUpdateOne) AddManualAdjustment(v int) *LotteryUserStatsUpdateOne {
	_u.mutation.AddManualAdjustment(v)
	return _u
}

// SetSpendOffsetCents sets the "spend_offset_cents" field.
func (_u *LotteryUserStatsUpdateOne) SetSpendOffsetCents(v int64) *LotteryUserStatsUpdateOne {
	_u.mutation.ResetSpendOffsetCents()
	_u.mutation.SetSpendOffsetCents(v)
	return _u
}

// SetNillableSpendOffsetCents sets the "spend_offset_cents" field if the given value is not nil.
func (_u *LotteryUserStatsUpdateOne) SetNillableSpendOffsetCents(v *int64) *LotteryUserStatsUpdateOne {
	if v != nil {
		_u.SetSpendOffsetCents(*v)
	}
	return _u
}

// AddSpendOffsetCents adds value to the "spend_offset_cents" field.
func (_u *LotteryUserStatsUpdateOne) AddSpendOffsetCents(v int64) *LotteryUserStatsUpdateOne {
	_u.mutation.AddSpendOffsetCents(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryUserStatsUpdateOne) SetUpdatedAt(v time.Time) *LotteryUserStatsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LotteryUserStatsMutation object of the builder.
func (_u *LotteryUserStatsUpdateOne) Mutation() *LotteryUserStatsMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryUserStatsUpdate builder.
func (_u *LotteryUserStatsUpdateOne) Where(ps ...predicate.LotteryUserStats) *LotteryUserStatsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryUserStatsUpdateOne) Select(field string, fields ...string) *LotteryUserStatsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryUserStats entity.
func (_u *LotteryUserStatsUpdateOne) Save(ctx context.Context) (*LotteryUserStats, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryUserStatsUpdateOne) SaveX(ctx context.Context) *LotteryUserStats {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryUserStatsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryUserStatsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryUserStatsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotteryuserstats.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LotteryUserStatsUpdateOne) sqlSave(ctx context.Context) (_node *LotteryUserStats, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotteryuserstats.Table, lotteryuserstats.Columns, sqlgraph.NewFieldSpec(lotteryuserstats.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryUserStats.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryuserstats.FieldID)
		for _, f := range fields {
			if !lotteryuserstats.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryuserstats.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotteryuserstats.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotteryuserstats.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstDrawGranted(); ok {
		_spec.SetField(lotteryuserstats.FieldFirstDrawGranted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BaselineAt(); ok {
		_spec.SetField(lotteryuserstats.FieldBaselineAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ManualAdjustment(); ok {
		_spec.SetField(lotteryuserstats.FieldManualAdjustment, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedManualAdjustment(); ok {
		_spec.AddField(lotteryuserstats.FieldManualAdjustment, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SpendOffsetCents(); ok {
		_spec.SetField(lotteryuserstats.FieldSpendOffsetCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSpendOffsetCents(); ok {
		_spec.AddField(lotteryuserstats.FieldSpendOffsetCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryuserstats.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &LotteryUserStats{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryuserstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
