// Code generated by ent, DO NOT EDIT.

package lotteryuserstats

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lotteryuserstats type in the database.
	Label = "lottery_user_stats"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldFirstDrawGranted holds the string denoting the first_draw_granted field in the database.
	FieldFirstDrawGranted = "first_draw_granted"
	// FieldBaselineAt holds the string denoting the baseline_at field in the database.
	FieldBaselineAt = "baseline_at"
	// FieldManualAdjustment holds the string denoting the manual_adjustment field in the database.
	FieldManualAdjustment = "manual_adjustment"
	// FieldSpendOffsetCents holds the string denoting the spend_offset_cents field in the database.
	FieldSpendOffsetCents = "spend_offset_cents"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the lotteryuserstats in the database.
	Table = "lottery_user_stats"
)

// Columns holds all SQL columns for lotteryuserstats fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldFirstDrawGranted,
	FieldBaselineAt,
	FieldManualAdjustment,
	FieldSpendOffsetCents,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFirstDrawGranted holds the default value on creation for the "first_draw_granted" field.
	DefaultFirstDrawGranted bool
	// DefaultManualAdjustment holds the default value on creation for the "manual_adjustment" field.
	DefaultManualAdjustment int
	// DefaultSpendOffsetCents holds the default value on creation for the "spend_offset_cents" field.
	DefaultSpendOffsetCents int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryUserStats queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByFirstDrawGranted orders the results by the first_draw_granted field.
func ByFirstDrawGranted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstDrawGranted, opts...).ToFunc()
}

// ByBaselineAt orders the results by the baseline_at field.
func ByBaselineAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaselineAt, opts...).ToFunc()
}

// ByManualAdjustment orders the results by the manual_adjustment field.
func ByManualAdjustment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualAdjustment, opts...).ToFunc()
}

// BySpendOffsetCents orders the results by the spend_offset_cents field.
func BySpendOffsetCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpendOffsetCents, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
