// Code generated by ent, DO NOT EDIT.

package lotteryuserstats

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldUserID, v))
}

// FirstDrawGranted applies equality check predicate on the "first_draw_granted" field. It's identical to FirstDrawGrantedEQ.
func FirstDrawGranted(v bool) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldFirstDrawGranted, v))
}

// BaselineAt applies equality check predicate on the "baseline_at" field. It's identical to BaselineAtEQ.
func BaselineAt(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldBaselineAt, v))
}

// ManualAdjustment applies equality check predicate on the "manual_adjustment" field. It's identical to ManualAdjustmentEQ.
func ManualAdjustment(v int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldManualAdjustment, v))
}

// SpendOffsetCents applies equality check predicate on the "spend_offset_cents" field. It's identical to SpendOffsetCentsEQ.
func SpendOffsetCents(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldSpendOffsetCents, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLTE(FieldUserID, v))
}

// FirstDrawGrantedEQ applies the EQ predicate on the "first_draw_granted" field.
func FirstDrawGrantedEQ(v bool) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldFirstDrawGranted, v))
}

// FirstDrawGrantedNEQ applies the NEQ predicate on the "first_draw_granted" field.
func FirstDrawGrantedNEQ(v bool) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldFirstDrawGranted, v))
}

// BaselineAtEQ applies the EQ predicate on the "baseline_at" field.
func BaselineAtEQ(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldBaselineAt, v))
}

// BaselineAtNEQ applies the NEQ predicate on the "baseline_at" field.
func BaselineAtNEQ(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldBaselineAt, v))
}

// BaselineAtIn applies the In predicate on the "baseline_at" field.
func BaselineAtIn(vs ...time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldIn(FieldBaselineAt, vs...))
}

// BaselineAtNotIn applies the NotIn predicate on the "baseline_at" field.
func BaselineAtNotIn(vs ...time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNotIn(FieldBaselineAt, vs...))
}

// BaselineAtGT applies the GT predicate on the "baseline_at" field.
func BaselineAtGT(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGT(FieldBaselineAt, v))
}

// BaselineAtGTE applies the GTE predicate on the "baseline_at" field.
func BaselineAtGTE(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGTE(FieldBaselineAt, v))
}

// BaselineAtLT applies the LT predicate on the "baseline_at" field.
func BaselineAtLT(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLT(FieldBaselineAt, v))
}

// BaselineAtLTE applies the LTE predicate on the "baseline_at" field.
func BaselineAtLTE(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLTE(FieldBaselineAt, v))
}

// ManualAdjustmentEQ applies the EQ predicate on the "manual_adjustment" field.
func ManualAdjustmentEQ(v int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldManualAdjustment, v))
}

// ManualAdjustmentNEQ applies the NEQ predicate on the "manual_adjustment" field.
func ManualAdjustmentNEQ(v int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldManualAdjustment, v))
}

// ManualAdjustmentIn applies the In predicate on the "manual_adjustment" field.
func ManualAdjustmentIn(vs ...int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldIn(FieldManualAdjustment, vs...))
}

// ManualAdjustmentNotIn applies the NotIn predicate on the "manual_adjustment" field.
func ManualAdjustmentNotIn(vs ...int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNotIn(FieldManualAdjustment, vs...))
}

// ManualAdjustmentGT applies the GT predicate on the "manual_adjustment" field.
func ManualAdjustmentGT(v int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGT(FieldManualAdjustment, v))
}

// ManualAdjustmentGTE applies the GTE predicate on the "manual_adjustment" field.
func ManualAdjustmentGTE(v int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGTE(FieldManualAdjustment, v))
}

// ManualAdjustmentLT applies the LT predicate on the "manual_adjustment" field.
func ManualAdjustmentLT(v int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLT(FieldManualAdjustment, v))
}

// ManualAdjustmentLTE applies the LTE predicate on the "manual_adjustment" field.
func ManualAdjustmentLTE(v int) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLTE(FieldManualAdjustment, v))
}

// SpendOffsetCentsEQ applies the EQ predicate on the "spend_offset_cents" field.
func SpendOffsetCentsEQ(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldSpendOffsetCents, v))
}

// SpendOffsetCentsNEQ applies the NEQ predicate on the "spend_offset_cents" field.
func SpendOffsetCentsNEQ(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldSpendOffsetCents, v))
}

// SpendOffsetCentsIn applies the In predicate on the "spend_offset_cents" field.
func SpendOffsetCentsIn(vs ...int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldIn(FieldSpendOffsetCents, vs...))
}

// SpendOffsetCentsNotIn applies the NotIn predicate on the "spend_offset_cents" field.
func SpendOffsetCentsNotIn(vs ...int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNotIn(FieldSpendOffsetCents, vs...))
}

// SpendOffsetCentsGT applies the GT predicate on the "spend_offset_cents" field.
func SpendOffsetCentsGT(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGT(FieldSpendOffsetCents, v))
}

// SpendOffsetCentsGTE applies the GTE predicate on the "spend_offset_cents" field.
func SpendOffsetCentsGTE(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGTE(FieldSpendOffsetCents, v))
}

// SpendOffsetCentsLT applies the LT predicate on the "spend_offset_cents" field.
func SpendOffsetCentsLT(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLT(FieldSpendOffsetCents, v))
}

// SpendOffsetCentsLTE applies the LTE predicate on the "spend_offset_cents" field.
func SpendOffsetCentsLTE(v int64) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLTE(FieldSpendOffsetCents, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryUserStats) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryUserStats) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryUserStats) predicate.LotteryUserStats {
	return predicate.LotteryUserStats(sql.NotPredicates(p))
}
