// Code generated by ent, DO NOT EDIT.

package lotteryprize

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lotteryprize type in the database.
	Label = "lottery_prize"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrizeType holds the string denoting the prize_type field in the database.
	FieldPrizeType = "prize_type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldMinTier holds the string denoting the min_tier field in the database.
	FieldMinTier = "min_tier"
	// FieldTierWeights holds the string denoting the tier_weights field in the database.
	FieldTierWeights = "tier_weights"
	// FieldStock holds the string denoting the stock field in the database.
	FieldStock = "stock"
	// FieldStockIssued holds the string denoting the stock_issued field in the database.
	FieldStockIssued = "stock_issued"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeActivity holds the string denoting the activity edge name in mutations.
	EdgeActivity = "activity"
	// Table holds the table name of the lotteryprize in the database.
	Table = "lottery_prizes"
	// ActivityTable is the table that holds the activity relation/edge.
	ActivityTable = "lottery_prizes"
	// ActivityInverseTable is the table name for the LotteryActivity entity.
	// It exists in this package in order to avoid circular dependency with the "lotteryactivity" package.
	ActivityInverseTable = "lottery_activities"
	// ActivityColumn is the table column denoting the activity relation/edge.
	ActivityColumn = "activity_id"
)

// Columns holds all SQL columns for lotteryprize fields.
var Columns = []string{
	FieldID,
	FieldActivityID,
	FieldName,
	FieldPrizeType,
	FieldValue,
	FieldWeight,
	FieldMinTier,
	FieldTierWeights,
	FieldStock,
	FieldStockIssued,
	FieldEnabled,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPrizeType holds the default value on creation for the "prize_type" field.
	DefaultPrizeType string
	// PrizeTypeValidator is a validator for the "prize_type" field. It is called by the builders before save.
	PrizeTypeValidator func(string) error
	// DefaultValue holds the default value on creation for the "value" field.
	DefaultValue float64
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// DefaultMinTier holds the default value on creation for the "min_tier" field.
	DefaultMinTier int
	// DefaultStock holds the default value on creation for the "stock" field.
	DefaultStock int
	// DefaultStockIssued holds the default value on creation for the "stock_issued" field.
	DefaultStockIssued int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryPrize queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrizeType orders the results by the prize_type field.
func ByPrizeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeType, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByMinTier orders the results by the min_tier field.
func ByMinTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinTier, opts...).ToFunc()
}

// ByStock orders the results by the stock field.
func ByStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStock, opts...).ToFunc()
}

// ByStockIssued orders the results by the stock_issued field.
func ByStockIssued(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStockIssued, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByActivityField orders the results by activity field.
func ByActivityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivityStep(), sql.OrderByField(field, opts...))
	}
}
func newActivityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
	)
}
