// Code generated by ent, DO NOT EDIT.

package lotteryprize

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldID, id))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldActivityID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldName, v))
}

// PrizeType applies equality check predicate on the "prize_type" field. It's identical to PrizeTypeEQ.
func PrizeType(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldPrizeType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldValue, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldWeight, v))
}

// MinTier applies equality check predicate on the "min_tier" field. It's identical to MinTierEQ.
func MinTier(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldMinTier, v))
}

// Stock applies equality check predicate on the "stock" field. It's identical to StockEQ.
func Stock(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldStock, v))
}

// StockIssued applies equality check predicate on the "stock_issued" field. It's identical to StockIssuedEQ.
func StockIssued(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldStockIssued, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldUpdatedAt, v))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...int64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldActivityID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContainsFold(FieldName, v))
}

// PrizeTypeEQ applies the EQ predicate on the "prize_type" field.
func PrizeTypeEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldPrizeType, v))
}

// PrizeTypeNEQ applies the NEQ predicate on the "prize_type" field.
func PrizeTypeNEQ(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldPrizeType, v))
}

// PrizeTypeIn applies the In predicate on the "prize_type" field.
func PrizeTypeIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldPrizeType, vs...))
}

// PrizeTypeNotIn applies the NotIn predicate on the "prize_type" field.
func PrizeTypeNotIn(vs ...string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldPrizeType, vs...))
}

// PrizeTypeGT applies the GT predicate on the "prize_type" field.
func PrizeTypeGT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldPrizeType, v))
}

// PrizeTypeGTE applies the GTE predicate on the "prize_type" field.
func PrizeTypeGTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldPrizeType, v))
}

// PrizeTypeLT applies the LT predicate on the "prize_type" field.
func PrizeTypeLT(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldPrizeType, v))
}

// PrizeTypeLTE applies the LTE predicate on the "prize_type" field.
func PrizeTypeLTE(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldPrizeType, v))
}

// PrizeTypeContains applies the Contains predicate on the "prize_type" field.
func PrizeTypeContains(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContains(FieldPrizeType, v))
}

// PrizeTypeHasPrefix applies the HasPrefix predicate on the "prize_type" field.
func PrizeTypeHasPrefix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasPrefix(FieldPrizeType, v))
}

// PrizeTypeHasSuffix applies the HasSuffix predicate on the "prize_type" field.
func PrizeTypeHasSuffix(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldHasSuffix(FieldPrizeType, v))
}

// PrizeTypeEqualFold applies the EqualFold predicate on the "prize_type" field.
func PrizeTypeEqualFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEqualFold(FieldPrizeType, v))
}

// PrizeTypeContainsFold applies the ContainsFold predicate on the "prize_type" field.
func PrizeTypeContainsFold(v string) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldContainsFold(FieldPrizeType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldValue, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldWeight, v))
}

// MinTierEQ applies the EQ predicate on the "min_tier" field.
func MinTierEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldMinTier, v))
}

// MinTierNEQ applies the NEQ predicate on the "min_tier" field.
func MinTierNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldMinTier, v))
}

// MinTierIn applies the In predicate on the "min_tier" field.
func MinTierIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldMinTier, vs...))
}

// MinTierNotIn applies the NotIn predicate on the "min_tier" field.
func MinTierNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldMinTier, vs...))
}

// MinTierGT applies the GT predicate on the "min_tier" field.
func MinTierGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldMinTier, v))
}

// MinTierGTE applies the GTE predicate on the "min_tier" field.
func MinTierGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldMinTier, v))
}

// MinTierLT applies the LT predicate on the "min_tier" field.
func MinTierLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldMinTier, v))
}

// MinTierLTE applies the LTE predicate on the "min_tier" field.
func MinTierLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldMinTier, v))
}

// TierWeightsIsNil applies the IsNil predicate on the "tier_weights" field.
func TierWeightsIsNil() predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIsNull(FieldTierWeights))
}

// TierWeightsNotNil applies the NotNil predicate on the "tier_weights" field.
func TierWeightsNotNil() predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotNull(FieldTierWeights))
}

// StockEQ applies the EQ predicate on the "stock" field.
func StockEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldStock, v))
}

// StockNEQ applies the NEQ predicate on the "stock" field.
func StockNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldStock, v))
}

// StockIn applies the In predicate on the "stock" field.
func StockIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldStock, vs...))
}

// StockNotIn applies the NotIn predicate on the "stock" field.
func StockNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldStock, vs...))
}

// StockGT applies the GT predicate on the "stock" field.
func StockGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldStock, v))
}

// StockGTE applies the GTE predicate on the "stock" field.
func StockGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldStock, v))
}

// StockLT applies the LT predicate on the "stock" field.
func StockLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldStock, v))
}

// StockLTE applies the LTE predicate on the "stock" field.
func StockLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldStock, v))
}

// StockIssuedEQ applies the EQ predicate on the "stock_issued" field.
func StockIssuedEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldStockIssued, v))
}

// StockIssuedNEQ applies the NEQ predicate on the "stock_issued" field.
func StockIssuedNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldStockIssued, v))
}

// StockIssuedIn applies the In predicate on the "stock_issued" field.
func StockIssuedIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldStockIssued, vs...))
}

// StockIssuedNotIn applies the NotIn predicate on the "stock_issued" field.
func StockIssuedNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldStockIssued, vs...))
}

// StockIssuedGT applies the GT predicate on the "stock_issued" field.
func StockIssuedGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldStockIssued, v))
}

// StockIssuedGTE applies the GTE predicate on the "stock_issued" field.
func StockIssuedGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldStockIssued, v))
}

// StockIssuedLT applies the LT predicate on the "stock_issued" field.
func StockIssuedLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldStockIssued, v))
}

// StockIssuedLTE applies the LTE predicate on the "stock_issued" field.
func StockIssuedLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldStockIssued, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasActivity applies the HasEdge predicate on the "activity" edge.
func HasActivity() predicate.LotteryPrize {
	return predicate.LotteryPrize(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivityWith applies the HasEdge predicate on the "activity" edge with a given conditions (other predicates).
func HasActivityWith(preds ...predicate.LotteryActivity) predicate.LotteryPrize {
	return predicate.LotteryPrize(func(s *sql.Selector) {
		step := newActivityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryPrize) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryPrize) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryPrize) predicate.LotteryPrize {
	return predicate.LotteryPrize(sql.NotPredicates(p))
}
