// Code generated by ent, DO NOT EDIT.

package lotteryactivity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lotteryactivity type in the database.
	Label = "lottery_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRulesVersion holds the string denoting the rules_version field in the database.
	FieldRulesVersion = "rules_version"
	// FieldTierMode holds the string denoting the tier_mode field in the database.
	FieldTierMode = "tier_mode"
	// FieldTierThresholds holds the string denoting the tier_thresholds field in the database.
	FieldTierThresholds = "tier_thresholds"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePrizes holds the string denoting the prizes edge name in mutations.
	EdgePrizes = "prizes"
	// Table holds the table name of the lotteryactivity in the database.
	Table = "lottery_activities"
	// PrizesTable is the table that holds the prizes relation/edge.
	PrizesTable = "lottery_prizes"
	// PrizesInverseTable is the table name for the LotteryPrize entity.
	// It exists in this package in order to avoid circular dependency with the "lotteryprize" package.
	PrizesInverseTable = "lottery_prizes"
	// PrizesColumn is the table column denoting the prizes relation/edge.
	PrizesColumn = "activity_id"
)

// Columns holds all SQL columns for lotteryactivity fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldStatus,
	FieldRulesVersion,
	FieldTierMode,
	FieldTierThresholds,
	FieldStartsAt,
	FieldEndsAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultRulesVersion holds the default value on creation for the "rules_version" field.
	DefaultRulesVersion int
	// DefaultTierMode holds the default value on creation for the "tier_mode" field.
	DefaultTierMode string
	// TierModeValidator is a validator for the "tier_mode" field. It is called by the builders before save.
	TierModeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRulesVersion orders the results by the rules_version field.
func ByRulesVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRulesVersion, opts...).ToFunc()
}

// ByTierMode orders the results by the tier_mode field.
func ByTierMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierMode, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrizesCount orders the results by prizes count.
func ByPrizesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrizesStep(), opts...)
	}
}

// ByPrizes orders the results by prizes terms.
func ByPrizes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrizesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPrizesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrizesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PrizesTable, PrizesColumn),
	)
}
