// Code generated by ent, DO NOT EDIT.

package lotteryactivity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldStatus, v))
}

// RulesVersion applies equality check predicate on the "rules_version" field. It's identical to RulesVersionEQ.
func RulesVersion(v int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldRulesVersion, v))
}

// TierMode applies equality check predicate on the "tier_mode" field. It's identical to TierModeEQ.
func TierMode(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldTierMode, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldEndsAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldContainsFold(FieldStatus, v))
}

// RulesVersionEQ applies the EQ predicate on the "rules_version" field.
func RulesVersionEQ(v int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldRulesVersion, v))
}

// RulesVersionNEQ applies the NEQ predicate on the "rules_version" field.
func RulesVersionNEQ(v int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldRulesVersion, v))
}

// RulesVersionIn applies the In predicate on the "rules_version" field.
func RulesVersionIn(vs ...int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldRulesVersion, vs...))
}

// RulesVersionNotIn applies the NotIn predicate on the "rules_version" field.
func RulesVersionNotIn(vs ...int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldRulesVersion, vs...))
}

// RulesVersionGT applies the GT predicate on the "rules_version" field.
func RulesVersionGT(v int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldRulesVersion, v))
}

// RulesVersionGTE applies the GTE predicate on the "rules_version" field.
func RulesVersionGTE(v int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldRulesVersion, v))
}

// RulesVersionLT applies the LT predicate on the "rules_version" field.
func RulesVersionLT(v int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldRulesVersion, v))
}

// RulesVersionLTE applies the LTE predicate on the "rules_version" field.
func RulesVersionLTE(v int) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldRulesVersion, v))
}

// TierModeEQ applies the EQ predicate on the "tier_mode" field.
func TierModeEQ(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldTierMode, v))
}

// TierModeNEQ applies the NEQ predicate on the "tier_mode" field.
func TierModeNEQ(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldTierMode, v))
}

// TierModeIn applies the In predicate on the "tier_mode" field.
func TierModeIn(vs ...string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldTierMode, vs...))
}

// TierModeNotIn applies the NotIn predicate on the "tier_mode" field.
func TierModeNotIn(vs ...string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldTierMode, vs...))
}

// TierModeGT applies the GT predicate on the "tier_mode" field.
func TierModeGT(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldTierMode, v))
}

// TierModeGTE applies the GTE predicate on the "tier_mode" field.
func TierModeGTE(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldTierMode, v))
}

// TierModeLT applies the LT predicate on the "tier_mode" field.
func TierModeLT(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldTierMode, v))
}

// TierModeLTE applies the LTE predicate on the "tier_mode" field.
func TierModeLTE(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldTierMode, v))
}

// TierModeContains applies the Contains predicate on the "tier_mode" field.
func TierModeContains(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldContains(FieldTierMode, v))
}

// TierModeHasPrefix applies the HasPrefix predicate on the "tier_mode" field.
func TierModeHasPrefix(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldHasPrefix(FieldTierMode, v))
}

// TierModeHasSuffix applies the HasSuffix predicate on the "tier_mode" field.
func TierModeHasSuffix(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldHasSuffix(FieldTierMode, v))
}

// TierModeEqualFold applies the EqualFold predicate on the "tier_mode" field.
func TierModeEqualFold(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEqualFold(FieldTierMode, v))
}

// TierModeContainsFold applies the ContainsFold predicate on the "tier_mode" field.
func TierModeContainsFold(v string) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldContainsFold(FieldTierMode, v))
}

// TierThresholdsIsNil applies the IsNil predicate on the "tier_thresholds" field.
func TierThresholdsIsNil() predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIsNull(FieldTierThresholds))
}

// TierThresholdsNotNil applies the NotNil predicate on the "tier_thresholds" field.
func TierThresholdsNotNil() predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotNull(FieldTierThresholds))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldStartsAt, v))
}

// StartsAtIsNil applies the IsNil predicate on the "starts_at" field.
func StartsAtIsNil() predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIsNull(FieldStartsAt))
}

// StartsAtNotNil applies the NotNil predicate on the "starts_at" field.
func StartsAtNotNil() predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotNull(FieldStartsAt))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldEndsAt, v))
}

// EndsAtIsNil applies the IsNil predicate on the "ends_at" field.
func EndsAtIsNil() predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIsNull(FieldEndsAt))
}

// EndsAtNotNil applies the NotNil predicate on the "ends_at" field.
func EndsAtNotNil() predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotNull(FieldEndsAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPrizes applies the HasEdge predicate on the "prizes" edge.
func HasPrizes() predicate.LotteryActivity {
	return predicate.LotteryActivity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PrizesTable, PrizesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrizesWith applies the HasEdge predicate on the "prizes" edge with a given conditions (other predicates).
func HasPrizesWith(preds ...predicate.LotteryPrize) predicate.LotteryActivity {
	return predicate.LotteryActivity(func(s *sql.Selector) {
		step := newPrizesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryActivity) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryActivity) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryActivity) predicate.LotteryActivity {
	return predicate.LotteryActivity(sql.NotPredicates(p))
}
